---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  interval: 15m
  chart:
    spec:
      chart: blocky
      version: 16.6.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # -- some general blocky settings
    blocky:
      # -- Enable prometheus annotations
      enablePrometheus: false
    service:
      dns:
        enabled: true
        externalTrafficPolicy: Local
        loadBalancerIP: ${BLOCKY_IP}
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
      dot:
        enabled: true
        externalTrafficPolicy: Local
        loadBalancerIP: ${BLOCKY_IP}
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
      https:
        enabled: true
        externalTrafficPolicy: Local
        loadBalancerIP: ${BLOCKY_IP}
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky

    # -- set blocking settings using Lists
    # Primarily designed for inclusion in the TrueNAS SCALE GUI
    blocking:
      # -- Sets the blocktype
      blockType: nxDomain
      # -- Sets the block ttl
      blockTTL: 6h
      # -- Sets the block refreshPeriod
      refreshPeriod: 4h
      # -- Sets the block download timeout
      downloadTimeout: 60s
      # -- Sets the block download attempt count
      downloadAttempts: 3
      # -- Sets the block download cooldown
      downloadCooldown: 5s
      # -- Set the start strategy (blocking | failOnError | fast)
      startStrategy: fast
      # -- Sets how many list-groups can be processed at the same time
      processingConcurrency: 8
      # --  Add blocky whitelists
      # `default` name is reservered for TrueCharts included default whitelist
      # example shows the structure, though name should be changed when used
      whitelist:
        []
        # - name: default
        #  lists:
        #   - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/optional-list.txt
        #   - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
        #   - https://raw.githubusercontent.com/rahilpathan/pihole-whitelist/main/1.LowWL.txt

      # -- Blocky blacklists
      # `default` name is reservered for TrueCharts included default blacklist
      # example shows the structure, though name should be changed when used
      blacklist:
        []
        # - name: default
        #  lists:
        #   - https://big.oisd.nl/domainswild

      # -- Blocky clientGroupsBlock
      clientGroupsBlock:
        - name: default
          groups:
            - default

    k8sgateway:
      enabled: true
      # -- list of processed domains
      domains:
        - domain: "${DOMAIN_0}"
          # -- Optional configuration option for DNS01 challenge that will redirect all acme
          # challenge requests to external cloud domain (e.g. managed by cert-manager)
          # See: https://cert-manager.io/docs/configuration/acme/dns01/
          dnsChallenge:
            enabled: false
            domain: dns01.clouddns.com

      forward:
        enabled: false
        primary: tls://1.1.1.1
        secondary: tls://1.0.0.1
        options:
          - name: tls_servername
            value: cloudflare-dns.com

    configmap:
      dashboard:
        enabled: false
      datasource:
        enabled: false

    metrics:
      main:
        enabled: false
    redis:
      enabled: true
      includeCommon: true
    # CANNOT be defined in above yaml section
    queryLog:
      # optional one of: mysql, postgresql, csv, csv-client. If empty, log to console
      type: ""

    cnpg:
      main:
        enabled: false
