---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fireflyiii
  namespace: fireflyiii
spec:
  interval: 15m
  chart:
    spec:
      chart: fireflyiii
      version: 27.11.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: LoadBalancer
    cnpg:
      main:
        mode: recovery
        backups:
          enabled: true
          revision: "1"
          credentials: mys3
        recovery:
          # revision: "x"
          credentials: mys3
    credentials:
      mys3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3BUCKETNAME}"
        #path: "/esphome"
        accessKey: "${S3APIKEYID}"
        secretKey: "${S3APIKEY}"
        encrKey: "${S3KEY}"
    ingress:
      main:
        enabled: true
        hosts:
          - host: fireflyiii.${INGRESS_URL}
            paths:
              - path: /
                pathType: Prefix
                overrideService:
                  name: main
                  port: 10082
        tls:
          - hosts:
              - fireflyiii.${INGRESS_URL}
            certificateIssuer: "domain-0-le-prod"
        integrations:
          certManager:
            enabled: true
            certificateIssuer: "domain-0-le-prod"
          homepage:
            enabled: true
            group: Finance
            widget:
              enabled: false
