---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: corekeeper
  namespace: corekeeper
spec:
  interval: 15m
  chart:
    spec:
      chart: corekeeper
      version: 7.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                GAME_ID: "1963720"
                GAME_PARAMS: "-gameid ${COREKEEPER_GAME_ID} -worldmode Hard"
                PASSWRD: ""
                USERNAME: ""
                VALIDATE: "false"
                WORLD_INDEX: "0"
                WORLD_NAME: "Synda's Core Keeper"
    persistence:
      serverfiles:
        volsync:
          - name: april2025
            type: restic
            cleanupCachePVC: true
            credentials: mys3
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: "0 7 * * *"
    credentials:
      mys3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3BUCKETNAME}"
        accessKey: "${S3APIKEYID}"
        secretKey: "${S3APIKEY}"
        encrKey: "${S3KEY}"
