---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: corekeeper
  namespace: corekeeper
spec:
  interval: 15m
  chart:
    spec:
      chart: corekeeper
      version: 7.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${COREKEEPER_IP}
        ports:
          main:
            enabled: true
            port: 27015
            targetPort: 27015
    ingress:
      main:
        enabled: true
        hosts:
          - host: corekeeper.${INGRESS_URL}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - corekeeper.${INGRESS_URL}
        integrations:
          homepage:
            enabled: true
            group: Default
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                GAME_ID: "1963720"
                GAME_PARAMS: "-gameid 1234567"
                PASSWRD: ""
                USERNAME: ""
                VALIDATE: "false"
                WORLD_INDEX: "0"
                WORLD_NAME: Core Keeper Container
