---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trilium-notes
  namespace: trilium-notes
spec:
  interval: 15m
  chart:
    spec:
      chart: charts/trilium-notes
      version: 0.0.1
      sourceRef:
        kind: GitRepository
        name: cluster
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      main:
        enabled: true
        hosts:
          - host: triliumtest.${INGRESS_URL}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - triliumtest.${INGRESS_URL}
        integrations:
          homepage:
            enabled: true
            group: Tools
            widget:
              enabled: false
