---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: outline
  namespace: outline
spec:
  interval: 15m
  chart:
    spec:
      chart: outline
      version: 15.1.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                URL: https://outline.${DOMAIN_0}
                FORCE_HTTPS: true
                OIDC_CLIENT_ID: ${OUTLINE_OIDC_CLIENT_ID}
                OIDC_CLIENT_SECRET: ${OUTLINE_OIDC_CLIENT_SECRET}
                OIDC_AUTH_URI: https://auth.${DOMAIN_0}/api/oidc/authorization
                OIDC_TOKEN_URI: https://auth.${DOMAIN_0}/api/oidc/token
                OIDC_USERINFO_URI: https://auth.${DOMAIN_0}/api/oidc/userinfo
                OIDC_USERNAME_CLAIM: preferred_username
                OIDC_DISPLAY_NAME: Authelia
                OIDC_SCOPES: openid offline_access profile email
                OIDC_LOGOUT_URI: https://auth.${DOMAIN_0}/logout
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          gethomepage.dev/instance: "internal"
        hosts:
          - host: outline.${INGRESS_URL}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - outline.${INGRESS_URL}
        integrations:
          traefik:
            enabled: false
          homepage:
            enabled: true
            group: Tools
            widget:
              enabled: false
    cnpg:
      main:
        #mode: recovery
        backups:
          enabled: true
          revision: "1"
          credentials: mys3
        recovery:
          #revision: "2"
          credentials: mys3
    credentials:
      mys3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3BUCKETNAME}"
        accessKey: "${S3APIKEYID}"
        secretKey: "${S3APIKEY}"
        encrKey: "${S3KEY}"
    persistence:
      data:
        volsync:
          - name: b2
            type: restic
            credentials: mys3
            dest:
              enabled: true
            src:
              enabled: true
