image:
  repository: triliumnext/notes
  pullPolicy: IfNotPresent
  tag: 0.91.6@sha256:689bc855d50d5adc08423801fa30838e2549cb6695fdffd284a8fe788e9559fa
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 10156
persistence:
  config:
    enabled: true
    mountPath: "/home/node"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 1000
