apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpinepod
  namespace: kube-system
  labels:
    app: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      restartPolicy: Always
      volumes:
        - name: devices-volume
          hostPath:
            path: /dev/vdb #location on host
      containers:
        - name: viewvgalp
          image: alpine
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /dev/vdb
              name: devices-volume
              readOnly: false
          command: ["/bin/sh", "-c", "apk add lvm2 && sleep 604800"]
