apiVersion: apps/v1
kind: Deployment
metadata:
  name: debianpod
  namespace: kube-system
  labels:
    app: debian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian
  template:
    metadata:
      labels:
        app: debian
    spec:
      restartPolicy: Always
      volumes:
        - name: devices-volume
          hostPath:
            path: /dev/vdb #location on host
      containers:
        - name: viewvg
          image: debian
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /dev/vdb
              name: devices-volume
              readOnly: false
          command: ["/bin/sh", "-c", "sleep 604800"]
