---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  interval: 15m
  chart:
    spec:
      chart: filebrowser
      version: 12.13.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: ${TZ}
    credentials:
      mys3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3BUCKETNAME}"
        accessKey: "${S3APIKEYID}"
        secretKey: "${S3APIKEY}"
        encrKey: "${S3KEY}"
    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            cleanupCachePVC: true
            credentials: mys3
            dest:
              enabled: true
            src:
              enabled: true
      database:
        volsync:
          - name: b2
            type: restic
            cleanupCachePVC: true
            credentials: mys3
            dest:
              enabled: true
            src:
              enabled: true
      data:
        enabled: true
        mountPath: /data
        type: nfs
        path: /mnt/MainPool/shared
        server: ${TRUENAS_EXTERNAL_IP}
    ingress:
      main:
        enabled: true
        ingressClassName: external
        #        annotations:
        #          nginx.ingress.kubernetes.io/auth-method: "GET"
        #          nginx.ingress.kubernetes.io/auth-url: "http://authelia.authelia.svc.cluster.local:9091/api/verify"
        #          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${DOMAIN_0}?rm=$request_method"
        #          nginx.ingress.kubernetes.io/auth-response-headers: "Remote-User,Remote-Name,Remote-Groups,Remote-Email"
        hosts:
          - host: filebrowser.${INGRESS_URL}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - filebrowser.${INGRESS_URL}
        integrations:
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "auth.${DOMAIN_0}"
          homepage:
            enabled: true
            group: Tools
            widget:
              enabled: false
#    workload:
#      main:
#        podSpec:
#          containers:
#            main:
#              command:
#                - "sleep"
#                - "90000"
#          command: "/filebrowser config set --auth.method=proxy --auth.header=Remote-User"
