apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: filebrowser2
  namespace: filebrowser
spec:
  parentRefs:
    - name: envoy-external
      namespace: envoy
      sectionName: https
  hostnames:
    - "filebrowser2.${INGRESS_URL}"
  rules:
    - backendRefs:
        - name: filebrowser
          port: 10187
      matches:
        - headers:
            - type: RegularExpression
              name: "Cookie"
              value: "authelia_session=.*"

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: filebrowser2
  namespace: filebrowser
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: filebrowser2
  extAuth:
    headersToExtAuth:
      - "accept"
      - "cookie"
      - "location"
      - "authorization"
      - "proxy-authorization"
      - "x-forwarded-proto"
    failOpen: false
    http:
      backendRefs:
        - name: "authelia"
          namespace: "authelia"
          port: 9091
      path: "/api/authz/ext-authz/"
      headersToBackend:
        - Remote-User
        - Remote-Groups
        - Remote-Name
        - Remote-Email

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: filebrowser-redurect-to-auth
  namespace: filebrowser
spec:
  parentRefs:
    - name: envoy-external
      namespace: envoy
      sectionName: https
  hostnames:
    - "filebrowser2.${INGRESS_URL}"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: auth.${DOMAIN_0}
            path:
              type: ReplaceFullPath
              replaceFullPath: "?rm=GET&rd=https%3A%2F%2Ffilebrowser2.${DOMAIN_0}%2F"
            statusCode: 301
      #matches:
      #  - path:
      #      value: "/foo"
