apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:x+khwsxuaR2AAwg+Sj+9wnNxw0EsMywnPA==,iv:ILZEIPqQYBzZJKdWrzOMb1mGBFJFRYsa0W/6Gphr2GE=,tag:4VO9WgAduN+w7XmZqF6MTg==,type:comment]
    #ENC[AES256_GCM,data:bJ6c0PF6dFYtCJnj,iv:qOBIGWXJHB6BPuL/2gKfFMsmMdr7Pz6rj1vyXGi7X3Q=,tag:pzGcCBtUDU9yDIc4GeedFA==,type:comment]
    UPTIME_KUMA_IP: ENC[AES256_GCM,data:RYgKQgjC/ht7IbmB,iv:cynLytvQv3X1t2IwvVD/gpnpH/h0969WfSzT9k3UTxg=,tag:Vxcgscylrhi696lLzlA82g==,type:str]
    FRIGATE_IP: ENC[AES256_GCM,data:qNob4HdtUo+h85Zb,iv:Qs2mOMYRqyQ1MqnI1rM4MiIbW/LHtQmFkXBUr0myMoQ=,tag:JqvrunvRcjNudPsZQtiPUQ==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:hsaM1+3jdIaGrb6K,iv:KoGlilLEvM/wBNcQkjuscWGqhjX9bfOd2qsZtA8mlbc=,tag:7NjTAd9LlO4c8XOEWlkqeg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:S8hbcdxtiH92Iqwl,iv:hmxE1TSIsy/mFSstiWPirZGwM3wour/iyClHrrpHM6I=,tag:/4YytwACTLnzgGXUjbXeEA==,type:str]
    WG_EASY_IP: ENC[AES256_GCM,data:qAfxX5SWk1VXzRU0,iv:t3ghDXKi8oY51tEV2KyvxQdD6gHoklaQKsegjKfcu+0=,tag:9+kKg/NPXy7hBRkvx9sSOA==,type:str]
    #ENC[AES256_GCM,data:alB0g/erXQz6w/lRg+QWGQ8=,iv:j/ig4yGbCVsU5L8NeniOE92+ydKviRzM0TgD5ArfvLI=,tag:JqShIo9adAy6uzHaT3na3A==,type:comment]
    FRIGATE_RTSP_PASS: ENC[AES256_GCM,data:8k9u79dF+FC6Ms0U,iv:M0Kw7DHVQ1JZHMXrXpcbjwMoNOclNeDAc+fzKGZJvHU=,tag:tGXFIBo1EjM40U5cDslg9Q==,type:str]
    #ENC[AES256_GCM,data:g9zNzx4+Sl1ZUpc6qHwT5mj3VCIKFWt32XWuN7x9knT/4GBCI/3j+htvxEKZ2J0Fc5uThcXeEAHF9dPJtLhe5v8=,iv:rhDwMIUq5kbn4f0MeRU8dyO+q81ucZu2+cQCUBnR/9g=,tag:diL7sV7KZATdtW+ShtG2kg==,type:comment]
    #ENC[AES256_GCM,data:Q1lEomsnT3dzI709HdSOMCzgYZZWWX0tJu7PAuVmbZLJRC5sQqjHI0s9DPs=,iv:8YbfU9n1H2kGHfroRMBQ7b7VcDzhI6KNj+1I/rO2fEM=,tag:EYmMQowFpp/Bh9w+HI13ag==,type:comment]
    VIP: ENC[AES256_GCM,data:t2xKJy8VMqHS7CM1,iv:ldrjksfOVqNvjQfw9YJbwEBppkyi6sd9eqjdu9wg+3o=,tag:7IccPuV/DMqsdsDfX6hTKA==,type:str]
    #ENC[AES256_GCM,data:eiGmmheYJ+scBdWq+lunBbTeFHxY9Dw00UQ=,iv:N+qsZcbijjj4QmP2GbrNL9YTIy8VAL4yfK+ol/y2pSQ=,tag:kTP4JjTUtyxrheNyLMbhhw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:cD1I9llFG2cYLhlKtg==,iv:2z26gTvES4SGXYBKYL5qpq3Yc1VDa4O0XQfnMvhfdyo=,tag:Xj616KLYrUKQNbqQWAsTWA==,type:str]
    #ENC[AES256_GCM,data:bcHSro/eCpFY4CfUwLFkENoLOx9gX/PZqtF5mz8JZzDMBw==,iv:uvE4lBpd/qtA+icE4AhCbXF1uN8TewuHO1VV1onehYQ=,tag:uXwc0KswEPXgM4Z2JJWdug==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:OOa7zzk45/JMgCI=,iv:y+T8ZAd669uc1VOr70vzKpT1clo1Ed3UdXLb/LGIDT4=,tag:Num+7ImufH/hcGYYzD1iEA==,type:str]
    #ENC[AES256_GCM,data:CGWGKYGYJyLHUPmXoiYE/jSgwUJ2zpcm+dzVmVdb3UBJYf4AS3qXzn3THP+SkoQ=,iv:QhPYMRT8ZayG9XZQlq8EttuImvhbXVNTDckR2JBXMUc=,tag:5uQ6JV6bZuVr+u1/k2fUaw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:SU3UQszgkZv9oMGb/kKnYcsCBgXe0e1F4w==,iv:T6vv+oCXXmS/2LhFhb6wwNdcZ/FDEvO2wL31rgg1Fhc=,tag:t4vWZUlCSqv24JU7h/7Otw==,type:str]
    #ENC[AES256_GCM,data:qDYdDmksundqlZOgA62Q+omVxDnnMDi6UeAS2xcgz54x9W6/C2wkMsvFfZC3NmAENaukE7KBqGFEAukj1QBPyK+/ODwuPl5OEbh9JGezuO4=,iv:JaOv8RsIoDLy/Zktp72IyNUpclOsgj9F0U58K4Ghu5g=,tag:LgBPSrJjl8epg2vjfk4Ptg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:Mv5/rkpqskZGri9e,iv:vrbuJIvxx/4xeY0CsuDq3CGUXnRrBGmJuKxeNlqHA4I=,tag:4G01zjxyi4hZKerinBHwGQ==,type:str]
    #ENC[AES256_GCM,data:A5ntG0Z0Tdpv3mZv87CujyqUUQGf7AtEDbwY4S2IKMUQByK/Zoh9FJmSS/zHcgO/rPV5XAMMDXo=,iv:wI8cODNsUTL/REF/mU/+lcSoK7cJltobpGIO0f5IRTE=,tag:TEBNGxwkDeIOQbN6unHtoQ==,type:comment]
    #ENC[AES256_GCM,data:xi564lsmJCyMnsBSG3aSthtlTTkaxx7EXg==,iv:0QvRk9QRUOGJskY+SELd5kk+dlduMPKKLxit2HHM8e4=,tag:9qnByvpEkBtIPf0Ipcd0dg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:lqotFf0DK99V8sCTVHI5Djwr6vxNcq8pHR5kUzIIc4sF7dH9j2nLd25MTwopHOHK,iv:pWrT0layhhV021KsfCnUhDO7npEMt/QhO7Vi7433KhA=,tag:j+U1fV/CEnOsiH9xnbSbQg==,type:str]
    #ENC[AES256_GCM,data:utoayIimfNfKYbHrcg==,iv:4apbPishIdjg0w3ALLvszD6HMGX17fJ31Q7XrNcrBuM=,tag:GA2Ub88KBWBrwmmdTGk3fg==,type:comment]
    PODNET: ENC[AES256_GCM,data:oZ/AOq+kP2BfPhe4eA==,iv:w0rJyWF60S9Gmb08B3qhhDOtzVV3GO2N1/9lGor10l0=,tag:86aR4XGJFI8arQJ9HGz1oQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:4Z+9GtKQRLU+0GwH/g==,iv:cCPkY6yQ8C9l8jEn2JotTBO4PALNc2CzS3CJfBu5kjU=,tag:VE9/+ROYId7AM7ZmAiXduA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:4bgsqw==,iv:Rjs6GBhU+vM9u2VbW2D6Tn6D4XYs14FMN46hodSSDFk=,tag:XMr8XdjNFu5gm+UuyZza4A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUDArVFl0TlBoNnkxWE1P
            c1d3Rm5uN05QQUV4eXNJRHAzSnRjelR2TTFRCndwZ0REcmVFb3pNc2R3dDkzRXNk
            RzB5YVB5ZDZKaEc2K21zUXo1S2tHeEUKLS0tIEJqaDczMjN6Y0s2VVlBLzJ3OFF3
            YUtpQW0yVEJmc0ZJMDB4WlJkY0h4Sk0KRwMt6LdznoHC6aI5uql+H4lmaZQ7FG8V
            fENTMFLQR8KhJAzWxIC7vGbKZbSjnm6UkJgByWjMbmeEKFvMz86Ypg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T00:08:07Z"
    mac: ENC[AES256_GCM,data:U52ZINLzSRRp/m8WMC120o2vbvBvv444sPIDOd8zt8TIYWWRJ2aURU2biCFUkNyirUmG3nVhvcEe96dBoJyFPlLdM7zT4qpYrZA8OWZQqUnbMTONqq1yCfJs0KSrgOCIiVc3Bl5aSahmMsE/qaPr2yrWcsSYggr28hU/wR3epdk=,iv:4k832XRfg2Jrowg/6kAjJyaSbsZjreel/XNhYJeoVLE=,tag:EDl9XTmQC49RNjhqImsz5A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
