apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:SCJ0g9yfSvWQEPyGbJeJLaYW/TRV1nmEcQ==,iv:VOB8EUu4C02/4jcJGI4MkBsJjs6mmWW6zCF0b8ZBMlc=,tag:FIpGEwPamTJONifZqGbsaA==,type:comment]
    #ENC[AES256_GCM,data:yLaWvtihY2bqx+GQ,iv:Y1PbHtc1b7xxdCac8CJz1UPqmdF3OtO5leNXldlBuHY=,tag:NG7JX5lGeL/zp7YahKKOwQ==,type:comment]
    UPTIME_KUMA_IP: ENC[AES256_GCM,data:Z/m+joiIJNMEb4Z4,iv:gY8uZPcjF9G5u6+9WMs64bdCirS1eHvIvaYdx6NNiu4=,tag:ieqLUpjtBw9kUCxyzH8j4A==,type:str]
    FRIGATE_IP: ENC[AES256_GCM,data:ET7onpcLkkBv0YH0,iv:/CxqeiXhP2wX5U/5Sym9t+RQ6GinkiADgH2BPWizc34=,tag:nTk9FuhEGnjCKuIJcvBfOQ==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:mIPqD2r2cuXMh87A,iv:Qz0tTFmRP6E+ilvi6FPstIW1Ny6sk4moH1T2EpNtt/k=,tag:XsgEJfizjg1PneaWC86nrg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:zEDaqO6r3AqAJQZk,iv:vODXkBJY/P6X018zZ0Prcc+2aey3GcINiZzsX4q/klA=,tag:niWOC1gsoxrVfEHYI/klbg==,type:str]
    #ENC[AES256_GCM,data:Op4l04+WDGuLcn49TaUYADw=,iv:1mhY6ZtUyx6rlDyKzZBwsgFQmzSDZ41OHbQPCIoptN8=,tag:62bNSKeuY+JLeG83ZxOM5A==,type:comment]
    FRIGATE_RTSP_PASS: ENC[AES256_GCM,data:4UIVMFVenffI/1+x,iv:WvyDqZkM6EniEr4aICLlHnAlGVrv7UgXSk70+bfp+Xw=,tag:kyDzrlfci6jkqyMIsOLzSA==,type:str]
    #ENC[AES256_GCM,data:Z5mn1iZmHcrdIV4DYpMYlUjl+u8m0M8SwajBzxv0CZ+XaYyOZmhT9KLr7w0IObKajCJSwgEAYMahSzNixmZDuUE=,iv:+3rjVUkmhU4o2HKEN84HTtQPbQhYZIgrz9yAT0jl3S8=,tag:7qCpjXYdCEresq3IElIdCQ==,type:comment]
    #ENC[AES256_GCM,data:AHBmlaIebOfK3L0Zs55u+1oHiM3f6bDv4e8o6HQHL/ifidehj5ulMfR/gk4=,iv:0UvUiDcF4eXzD+ke+WGvekfMU/sYZFsA7pulLgZRIGc=,tag:Jwfqisyr4teKw7wOOEwTFA==,type:comment]
    VIP: ENC[AES256_GCM,data:8PVrx4U1pcnr76t3,iv:Hi8yfwN48jjUpgWUDUde1ij9fQHmRDpnnOHIZepvEas=,tag:3yvIVr1iwnPnykh7kp+aMw==,type:str]
    #ENC[AES256_GCM,data:sFWuxn5e/uMBqTxtRqBkrGM9rGPplUeoHEM=,iv:bcSpeqDBrlfMWbstXa6UrhEf1AnURy2neQjLS/nDbbM=,tag:ElrbPUvzhpddy+TkrVaatg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:hcIMkhdYmISOWSRTbw==,iv:xuJQSE0giVrF4r9wYQmsOMPKElsdzapNBND3qJDOmzM=,tag:L1S8XJFshHarIIk1Jd4q9A==,type:str]
    #ENC[AES256_GCM,data:SJl7ZFOgyeoS3l7bzJz8Z/YJSnc6OwtdP+5SmFj3aJZ2TA==,iv:MaTW6yHFadjK6XnTYj/1+Seq+3igs/W7DHtxZqua45I=,tag:GM1+ADXE/oHVyWX7xUlVdA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:5Jz/fiA9Mp1GHFc=,iv:1vLWD3qhXiQVmuEizS5g6nmHzAsJ1phRFC+ZWJd+GkM=,tag:7M50gnmqAe5GhH9i3R72gw==,type:str]
    #ENC[AES256_GCM,data:QxM+xjBoepLPVPYt+caO0R4JYtOTqJRsKXsa93GfxQyVhFNUFiGEyemo2Yt7EHk=,iv:fawaPq2iKnaf57pAvujqm3hgffGNzNOIwANdSbI0cVU=,tag:xqHM354Q/l/twn8bl5Sbkg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:mbyHEPtnWKXtIXe/X2CPAnJwADfP/bpgdw==,iv:F2/dkq6laXONzNShBfaTpNkYpxpUlZuQhatnoES8JJY=,tag:uEeVSGPnypUuZzpzf136/g==,type:str]
    #ENC[AES256_GCM,data:3+hDzhQn83T3Dsq6UnJ2zAQbUVqYR9KqmzPDctn5DnxWlIUd4cm1XNvyDVAFEmofKZATqkpCwM3wzRyZqk1LI5VhZRYE83dAYMN/2sbSqss=,iv:5z1fn0NRxBfr0pWSk7VCYFrB88jHtj5U1OqWzW/6k94=,tag:tLgnNFFSgStWI+TeyFzo2Q==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:ntAOUQ11LOMl60fR,iv:8VeDXKr5oaMjBrjvMEiFOASIembAtKOhvH2ZeTmS7ys=,tag:zRXLbgbNHii06rKJrQxblg==,type:str]
    #ENC[AES256_GCM,data:0FgdQrVmC2cG0gVM8BAUeHXOz7pzCITYrnAjsIe9D1sSDN9z9Ki/dfg0223dXiEEvdmAkfUa95M=,iv:+Kr2EK585WGhq7gGnIqp/t1LBNQLwrAxOtr9bdLB6HQ=,tag:7DMK0jzVcRexwVMOs2yRLg==,type:comment]
    #ENC[AES256_GCM,data:Gk08r9lEvqcedp1nE98ovjs225Ihit9EIQ==,iv:/mwqNl1yNSARrd+CfJ6yB4Y7CnIMmTn8k46nPYsz+PA=,tag:0sJK+RS3Eh1JnjI0dSzifA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:fq75LubfIQoFd3RGSFlBDBGIrEkNmIr3gRIGd5oYtB2kBEeUEGXimcSgp1L3n6K7,iv:uM7KKiXebcEL9HwqWi+kbdTxlcTC+RdKuunQIHweoVk=,tag:P6j2gY+KifOSaKf4cgXn3Q==,type:str]
    #ENC[AES256_GCM,data:rmIQkUtzbl1MMcjIvA==,iv:0MgdOq/oQ37lqpXpalK9X2hHHuTUke1zHtM3wG2lBHI=,tag:KGFcM+7jnxVmdu1JNO+YCA==,type:comment]
    PODNET: ENC[AES256_GCM,data:/rfmXG7FUqS4AcrxDA==,iv:MlzOeJZnRl0h+fe0p/ZlgqQbbPhOfrfSIV7iFzf1JuE=,tag:9oLYmd7mYXbMjUVPfBdVgw==,type:str]
    SVCNET: ENC[AES256_GCM,data:DePKHZPhSfPWFUcQFA==,iv:aqA/AJhAXvglik46JfA9fBhY9fVNVYjRr01jwQ9KBXg=,tag:Sf3SuB/DhOvMRjhxb7M2rA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:dqO31w==,iv:vAguFizfVILxdPPXrrQ3rVVSdMlAOM2wkAMHS90a1Do=,tag:iHyDXe4eKnR/7OLwYI0apQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaFkyY2tUUHduZGRGM3M5
            TEQzTXBmWlV4a1FGWkxCOUc0SUdJWnVCTWlzCnVmOTN1ZUExUEx1YTlaTldTaHBP
            WVNQdUx0MFBOZEtWaTBzcE1lSytsSUkKLS0tIG4yZU9WN0xBNDlqLzlTV3k5QVJn
            UWkydTFoeG14RHlTTUFWVTJHWXRzQ28K7nLGos7CB6pUz+hqEYpCTj7VqwcrzKNk
            UwoUP9vowcqDGQ4mnsrfCZy1XJ9vii7wY90CzOkHUNcBmTpj0acbOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T21:23:51Z"
    mac: ENC[AES256_GCM,data:zCb4Ip8/3CZcOfKCS3W0cxSkTwqHQdTkSveaaGn+77Yk1tLitw8TpArROk4qBv5BfmseAFucyHkO5qFJ2GDj45JPiA1o/fFOTiYfm1xtsdboV19gBTp6/GhgDPZBM+j/8/C9iJ3Ur++HLt86xeCNMuKd7EVf9EmWoFU5uByRlxQ=,iv:oVA/7gR8EYalaGSUKnp8WSAGmHj6Z2iMtdWVsZVICZg=,tag:Ha84eoEeCOKXi/4AOXIEnQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
