apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:pc2Vx+JVjvv///qN7WQV/HH4Dh/hKnGYZw==,iv:ZtiC8ju3RIdoYx5U5l39WZtPArp3BEKN6ZpE5wEzaSU=,tag:QA9DXlUdF9fyrF/2O19Scg==,type:comment]
    #ENC[AES256_GCM,data:S2VlxQkZShSBjXNX,iv:dsSUBfo1osBgYab74UBa2ZuvZK4/BliAivQR8q9Uc5Q=,tag:spjXtfimXt+BgCnQVyooyw==,type:comment]
    UPTIME_KUMA_IP: ENC[AES256_GCM,data:CDKpAjfdBqnFIcHr,iv:UfvYwIIMjPRQflFnWWojBHZ8DY0cX8kpRnIT7xjIyJY=,tag:hFisjp6ZXPxuvM849pqhRg==,type:str]
    FRIGATE_IP: ENC[AES256_GCM,data:VyqQ6ZoOHd8vaSBW,iv:rrFHsLPEn7TItywezcobQHc4rXRY6t0/Nx5n2E70b9I=,tag:HJAJKZ1XqWErxguKSk2r/w==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:pDk/PN1T57OordJF,iv:WnbwPbhatjrbRZhvDe1dcN/EjYS//kpHErbSPt7bT3s=,tag:s+cU/8wCV0Z27lxy8V48WA==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:3Kk3l2gKmzPK0cEn,iv:yA9l4yJRb++r6uBGqUYDm+t5Ysv03bH/odpkC/bYQ0Q=,tag:zk8QOKqqXAjv33eFrpSiBg==,type:str]
    WG_EASY_IP: ENC[AES256_GCM,data:hgpffSPYl9gyyd0x,iv:4rj4K/MpJhg9XCllUxml3vyS5zBE3Lan5QepHi0Azp4=,tag:rCOYFl+GZspCCFaFR83nRA==,type:str]
    #ENC[AES256_GCM,data:FS9goelNY01kb1HAA2PsHNM=,iv:4aVtmqTiccTm0/VCX6HlCwLrrM93OjdE9uWp8L7u1d8=,tag:HT0NQLiB6kl82VRxiKwUnA==,type:comment]
    FRIGATE_RTSP_PASS: ENC[AES256_GCM,data:W/bGs8IHkh7yCaT8,iv:hgxeQW8O//IJplW2p2dZShRB4wt0OAcxfBlzhFs99jI=,tag:0L/OImsAsvH2IGMIH/W5Bg==,type:str]
    #ENC[AES256_GCM,data:8UgoJ3pErMvDpQCxmoWPXwIDX/C+CxqSxx/GrsBwnyP6odzq6kEnGAvmlDYUeXKdltl9m/Ne8kLEMPNrmVJU+n4=,iv:M4lxvh+XOMRxUuoKxlyusMbQOq9UunJCdr0Zun80NEw=,tag:bz4qBrm3E9WWRpu58+zXNQ==,type:comment]
    #ENC[AES256_GCM,data:LHZr1IMrw8ShmlVGktTYnqYzjw0l8dnRw2+1unwKCdf9JhAcvB3CuDO16Xw=,iv:lYC2BMe0Us7dxrdLPXq+bRcXegw14eEGnKY7H8q9nMw=,tag:XZ+euQuJQxEat1vNnWJN+Q==,type:comment]
    VIP: ENC[AES256_GCM,data:pTOd4F1Nc23R3lfY,iv:anChSxc2+AFiaoxG2C9yfWQ6mYr0wzchgDd53FWmfvU=,tag:kod5HKrFuWXRWhpFC0h99w==,type:str]
    #ENC[AES256_GCM,data:FXJRO9tqhJyGUIJyhPQ5YRwJfOBlr3uAhe8=,iv:mM9kDH/fkwUqZmBJnNWYejrS4UNBR8QB4GDw2TCt+4o=,tag:EH0M9JtG8+gZYK0m49WI0A==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:9KkbEIylyfFYAy3dtA==,iv:ank3mgazw0Gs6PkomtFqYtaJGDdoQloyeu+KpFXKGnU=,tag:WbQJAUec9bSvWMWA0MCm0w==,type:str]
    #ENC[AES256_GCM,data:xGVxmFXhh2KfHiarwyGJtB4+LRNNJd/4vt+7mvxfxkBNSg==,iv:afKDJ+jL7kE/64wO+k9xPN9vVX7Kec1ysDlntamtduA=,tag:WQNZqGzObJX1Zvpa17I9HQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:KKtN25Qlh3ps750=,iv:dnpq3zKkOdDpD0iQLnf2JyLu5k4JP4kutAsrIWxh9IU=,tag:bj4NouVd/X3Z+UAel9mIDg==,type:str]
    #ENC[AES256_GCM,data:mesm+PA4wP+QbvtLmzqSaThA/FNmEEakCxB9mpW24MKNEIDa1UISzQ8OAl8cgW0=,iv:NB3cUb5LycnXdvug+jgxTi+2zn338KD9OFcCohMSpt4=,tag:7tDmPeLi5E4MYwKXWkR8Yg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:wtyympZ60OKpNrUI7hrdSJmIcwmXSxcjhA==,iv:sGAaDsYz+XqzWZGWumMMizZXAeIgPRSaR+ZO3bMeSyA=,tag:22R6OdXD65was0hgo9+qaw==,type:str]
    #ENC[AES256_GCM,data:uo4r6KYIehVDsWGjZcm7ZU/rtrOCLCZkOaKrRAT6X/c1PkjMMZvvnxUQrFH60kYpXtccVLSOdo4bSqr5Jg97V9+YCIYtXSEEBvVty2ouIIc=,iv:Izpr+HuFMiscuWzwzoy6x1P/tYqtke7WIWZrOiF/j4k=,tag:PCdQjppeQBm7MNN6wLWJsg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:nWuAlCPNDGGUwwCX,iv:rj38iMAxfPdGuiZjm+/dw7Dp7JrCfP0WkIjse0FrFew=,tag:Gn+k0ZF9aSpYumCdWnWjhQ==,type:str]
    #ENC[AES256_GCM,data:7XD+ovoVdPRFrhSHoicupvJhOoD38lBCbNmxrdhV1r14HD1auvEk2+8tmEhXc+gRIejZejjVt24=,iv:goXaobx0NEeq2gS2SwJhmDXCf7Hcu4GO+3tQupR+Xkg=,tag:WEX7BLbFki93K+Nd9MEAvA==,type:comment]
    #ENC[AES256_GCM,data:S3KD3GhP3Tn738JJ0uflehKU3C5gPUi/fg==,iv:Cmd2XyKKIw17ImD6ANytdBsnQFeWF7iFrSR0vYaBDig=,tag:J301V9B1UkEmcNLdH4cY4A==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:7BbAz9BQxB6WSvUjff7vyro72zgsVgXBHT9HfB8ul3R+gnAa+ji7OVyJydNhfkmY,iv:mDLMO1r+oBX8dGOF8Aw6FUEKvXm1gt3zfddikgrXFN4=,tag:J2POkkfqiyHEgm5wpJ26yw==,type:str]
    #ENC[AES256_GCM,data:3diccTGCAoATNBTaqQ==,iv:mqjH4FYiVIPnaiST6QCmJrbuCKh332LxiMd3D6qaQ20=,tag:U1NEHDWOJ0p0ZM1oAPV5Tw==,type:comment]
    PODNET: ENC[AES256_GCM,data:BUPkCqc7yRQTio44KQ==,iv:vsJy4t32Bdk8usxksppNwHeqcO2xqJMsY4E0oleFQnc=,tag:+aP1APktb8gbk5n7hOqGCg==,type:str]
    SVCNET: ENC[AES256_GCM,data:L+8mkslPKZQ9BXOR/w==,iv:lnq3cSqvi4sdrfRTKJQBPK/mCnR2TQyrj5WrIoyxd0A=,tag:06IzToHc5mZx/dZhQ/DrMA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:NQ4+Fw==,iv:LxcGOk8GUF9qZ/4Debz2I5qC/Zjv0V5rUR9wGW42p0w=,tag:yJroAn0XyCbQbXd10VAY6g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaG05YUR4NElTRnNkdmp3
            dm9tK0FhMm9QbHFNem5hWmg4c1hHc0hSMnpVCmJqa0FGVmVULzNrNmErUnQxSW9W
            aFJubkxnbXVhL1JwMVdxNVlxNTYrQ2sKLS0tIHlSeThtOTFaRkZWN25BOW94SytX
            WG9FeGlmL3N0R1hkWStId2lUY2U2MW8Kt9M+YRAI0xWE+PpUNdQqJWmwnBNhz7/l
            XBIDRS34LS9vHcBjmFpaeXBUdVuZqCasdECgCTLB7IdNVFN4W/aPSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T00:38:23Z"
    mac: ENC[AES256_GCM,data:xCwYkbTcEBFYZNfWWQ219zY52lPApm4H1AlZYbT5XBdunDII5w8mNYmzE1QfsL7ou8cl1ncUkp1B0yYscsz7h8PTiHEptrw1SE32hLQHiUOoAH0WafmEAS4bjrafeoWpQVdSrNZ9M0xQo6CvM8pq5yWDkRp1mdbd4qsz/rxiYDE=,iv:PS2iErADjGumjRf//UXU4KCWsrp01U+/XHeaBuMWXNQ=,tag:Zdiz25y+TIuKOaeNUnkLyQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
