apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:JEkVr5qalRlZ9HRPpmtgs1ajBFn8XINvCg==,iv:FnYicWc1dozUMOWT5PptEqHKI/rarXpf1Fs1gV/7ysg=,tag:ceCeoWUHpIfpUUljcSkx1w==,type:comment]
    #ENC[AES256_GCM,data:EAQwqcshw8gub5MP,iv:gzWSOpVAUoDVYpk70e376CwusRbyDJS0KWaF/mPIrbg=,tag:qv3c+Duf1NjeRJLc0fG75Q==,type:comment]
    UPTIME_KUMA_IP: ENC[AES256_GCM,data:GWHld+DMh09QAAdW,iv:yzjaAASon+fmdx+htDRClsq8vrz1waT2osAA0Y4qcbk=,tag:5JScp13S5GKEYbGNpKrKXg==,type:str]
    FRIGATE_IP: ENC[AES256_GCM,data:iHml9qhJr3BeM5ZG,iv:NEwHcXXGPVK6H+W45pgPKwQAcYov/wUqoKtV0EwitR8=,tag:ZYUzGcYXI48rKNuS7Y4qNA==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:gABWsc4OrJOKkDI9,iv:5yGTEX6sDHMOc7A9EF6TjAM+6Igh143B+5uKcWDyn1A=,tag:OLPpko26fClXiYvW5EXh4A==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:7gnEXMVfWHleuCJU,iv:qGR6Vh98R6gkvGeB+dLKQ3/5y69ADmUNlC4R56B2qMI=,tag:q24eEmXB3zl4/mEaoB/zdg==,type:str]
    #ENC[AES256_GCM,data:odTBUlu/Gv0Pr5Ptzvc/84Y=,iv:lzRc2fMGLLZ551tEznAwQMdAU5UaP49FwZUwuKQ3Ny8=,tag:8mY7vSMAJvCpHA47gw/EoQ==,type:comment]
    FRIGATE_RTSP_PASS: ENC[AES256_GCM,data:cNXXn53be6pHYuC+,iv:+FN4QbL0BPz8ZbkEpDHT7rzTC1Vu3HVS86Y6l/s7F3w=,tag:x+0ICdi932JoFYGAnUDYww==,type:str]
    #ENC[AES256_GCM,data:oN/Yo9mI9HdYyI1p1Bxbl1AvZ/tvo6HJWffAtsx/qJwseDeD4rWmzUQotSDjHLPt3Gi9MujOqSsH7zZRZMhlhyo=,iv:UWHZfWXxO3GtZNELCaK3E8Dk/fDEvZHJTkLOf/UnmYE=,tag:EspX/K21PiEcMm/XgfqulQ==,type:comment]
    #ENC[AES256_GCM,data:4gyl8BWXuUfa9AOapDuP2Cr9SY1LZl1pmZuQldc8qzys2leCnPGgdcD1q6g=,iv:Prz6BhWvT6zkTVhXyzQn8lzqIJ3UcvPZAWgxZufjncY=,tag:7TeQcPqFg6SozBqkfdrK8A==,type:comment]
    VIP: ENC[AES256_GCM,data:i/n4s2NdS/fBfmh6,iv:S3m1z3xGtNAhlYJl+KPq8FtBMWWPB9mGy2TdMSjezAM=,tag:y4YnaqOinkF+EWYIc0UWlQ==,type:str]
    #ENC[AES256_GCM,data:fTuSa1Kd2ctqeWT4X1P/HdKbfoThscL3X1s=,iv:GSOkCUs/6PKiOHMrjLkvcOrvLabQv7NeeLXjBH+zCoQ=,tag:aRaqdsn5PWQsR+BCC5ozXA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:etdPYOd9RqNPpZkEag==,iv:LdifFWVIbPRG/snUImY7Bgazoi3aYD4xblp5Pn+zmMs=,tag:XeNrVS4wB9WLemrgwyZbRQ==,type:str]
    #ENC[AES256_GCM,data:8EzQKVujUu1rtQ6J4MwCt8dQ44cD/dfcbfImCHjAMpqwcw==,iv:RkCC7LuAdqEmrdc2oUnvGi6fEFMUxJ7y2omKFlYoCag=,tag:5FMTkk8chWfRZNXV8k57iA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:sry715GjlCaB4nU=,iv:6yMCG3jZx8nX648dO8lQj70YB67qONAiUOesCOhcGY0=,tag:tWmb8Lp8Tu+hYokZHPr7yg==,type:str]
    #ENC[AES256_GCM,data:sbcaflyJy77Riyyn0BWWjZwzcQycZmvPNHjgeH7i1uXYJ/284bLmZaXHWJfx7hM=,iv:UUS/BsJG/OqO+R/w6TMvV3YMFvOILoLqIanUF8u/z2U=,tag:y29hTQaHtcbsNipl8rFixg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:+J1JWrEXKxiQzv9kZ0VuK9/uRQU0L4jFEg==,iv:V5L5HPvEnUHq9aa76fpmtI0Dd3BbF6jHRhqjfK/Dyr8=,tag:sKTb5FTrlOO8nsEmQZm9YA==,type:str]
    #ENC[AES256_GCM,data:QwlUZXr974/Y18lwOmaq9omdAGJ7tQQAzMOxqmZw1joWW3Z3OXzV/5IqXnaMUgzFcNgN7T55VEPGpT3v4OMNidLcF42hrPegjrGDRw4MQiY=,iv:C5CU4jOe0Zuur/yQy+oFJWuNZUY54YI7T+pCwHW3fW8=,tag:xddvT2KW7lXecl9jlhlVGg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:7pMP2isxunE1Ahws,iv:74jbTF6t04jHrFCgIrGa2stNC8zJ24qUW1y3hiLqMHM=,tag:kC5onbYy6YDb9juN0ihf5Q==,type:str]
    #ENC[AES256_GCM,data:RVSQtpFYcp8HypQS7wgXIWEyaR3hNanrAob0VWy/O0vvs1rHoraiLemhykARF03e3xjwsB4op8c=,iv:hNHgY97K0dgZNAShvQLk02AMFqxTICQUhrKRaW/EEuE=,tag:kxTt28il+xHc4tDDzddk/A==,type:comment]
    #ENC[AES256_GCM,data:n3K/HRyY5b/6B/8wxYr36t7bMXFJgeilgw==,iv:+NqolJA/Z0bwkByJj/FUzIaLBp6gwLTyPelchfLq/jc=,tag:eyfee8unVE54oRKTd4sVZQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:1bABIqYtyokOOka7h/A2GZSsZLgllLkULouu6TTuLtut14zb8h5Vdjh+aMP6FUZo,iv:YC3+Sl7Xla6wztyCJLebQkxtNV/48lbG2M1sx1lTjN4=,tag:iMCK0FNeXly9/JkL+sROXQ==,type:str]
    #ENC[AES256_GCM,data:z1qKxMboENgsvm+Q7w==,iv:afjXggcGmkE7w0qieg46T6d4r+4QNbR2ZiOqloFtrJ4=,tag:VlG2ICV2MknRmfXIgjTiNA==,type:comment]
    PODNET: ENC[AES256_GCM,data:LLTw7kOo6Uiod0Dn5w==,iv:lrUAap9eHQvsGOaYzLP3+XTK1TIcwmJPCq6FovSplG8=,tag:bYJrlmbGYwrldKmI/pPInw==,type:str]
    SVCNET: ENC[AES256_GCM,data:IT5APTAqaV4QW76bqg==,iv:coXSEB7dPtWCC5Y006XarwiM14bhBwtMceDMUif8OG0=,tag:ywcnh5ZTw8bTHjDp/DFHCA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:FdnZvQ==,iv:qOifL43slWtmcBgeyOMP+1xJsXdv6c9Hp0oOV9hf7tI=,tag:yorHdvyFQIrHG3ZdRrZ/+g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3T0FCUVF6aUo4bDlUR1p6
            NU83M2VlOGV4WlVjYTRvVmhmelJrcXlWcUFRCnNZOHZCOTBtOXB5S3RWeTlCSVJW
            enlsTVNCd1pkb3FDOUowWWhjR3ZueHMKLS0tIHBlSWFKU29sYlR5U1hFNmRwMU96
            aU5rYzRMOUZobEJJQ1VvNDY0Z0JPQlkKmf3IqmKd/sKNaezVhJIzjiWA5KUldyxT
            DMVMrUR4b1HYUraze0M9PwOtpCazLQ0I0qjepliG+YLKNT5+HuLs9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T21:55:38Z"
    mac: ENC[AES256_GCM,data:jScuYMSjQXRLWTAQpAaXeZuZ3kVQsOVQunLvzUDpdRT9lOrzF7x/wjSfsjvpHb54APb3mmFd/KVt8x6pFB2aF4yOgrOzMDk50+R/sWtOqUwtCQwaM9g1EEFYW8E+9ScYTo/FhvLYdbhMmxSodeALohOXmNnROipeAEhZXD+wi6Y=,iv:tHV0SyvS/wAOX9iKBl9SQmeNbSlM8dZaA5J7cDQIDI0=,tag:MdwYKtzqsCu6/RB4G23zAA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
