apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:aNrA2q/5HtugTss6k21IqPXjdeH3LvmB4Q==,iv:vZ2xS8FaCR+gk8vPj0hci1y5pzbzRN0JEs0apCjZboA=,tag:lvxsgz1uYxT/vmWORK4/Iw==,type:comment]
    #ENC[AES256_GCM,data:oYCEfDFmZn14U2ez,iv:sVUrADgVh3HXv187YnGzO7TxHl4QHPMMzJhZDLpQ0TI=,tag:r4ZcDP26EFLuFz1U4ixKaQ==,type:comment]
    UPTIME_KUMA_IP: ENC[AES256_GCM,data:0Gp2X25b5qnMNt2u,iv:Yx+6jtfyxgZYZFjE5w6aEDq3WHOARPC05W5fh9EhfUw=,tag:v1lUHa+g+h5AjuYMj5FDmg==,type:str]
    FRIGATE_IP: ENC[AES256_GCM,data:jbe3oqPZTZPH+6Is,iv:jE/8FYLtiBO6uF8yvUDnb3bkA/CxLsKeYyNlLK0OluA=,tag:3BBnHTKUVWtCjlhJH4UKGQ==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:ZxzqTDTTFpAUFXAR,iv:OX4ev0TQ/xotWpYC4on+UMxWBymu2HRUmxDp7pBmFXk=,tag:g92GhqxmVpDVFA0IxY58PQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:LtxhL8GEqwrAXS/e,iv:fsYYtazHsvVOhujQ/vE/yN141rM74GDKcW723nZ2Ldc=,tag:VAmPX9cxCWa36h6uaLhWTA==,type:str]
    WG_EASY_IP: ENC[AES256_GCM,data:2w6FQsJnJ4yluben,iv:YtEI8/AFlUzjCWIjkSy6kyuiAhtq5uP6lz8Beh5VTCs=,tag:SnL5LAsRHWmY+o5r6fRUHA==,type:str]
    MOSQUITTO_IP: ENC[AES256_GCM,data:JmIAV3Tu6GIENpbs,iv:8BpgoX8edfn/gOUPmaGboEJSM3gltJJrL1iZ8+JzMEM=,tag:kz0XokT3bBaMpPJ2JJ+oFQ==,type:str]
    LONGHORN_IP: ENC[AES256_GCM,data:DT57A7tCdDA/5rFi,iv:e4vHowa+Q3aJxRA9YAwmHI7bBwhfEUVacb/tGaSRHJk=,tag:Mp1HyBxNp4OskYCncDUmOg==,type:str]
    #ENC[AES256_GCM,data:GNGDCrQuQoM7awRN0ob4JHA=,iv:AKn4M9ndA2PN0o41YNufosO+7Vr4v+dXj8VGDPc0zCM=,tag:VelITcqbLq1CATke/hEd2A==,type:comment]
    INGRESS_URL: ENC[AES256_GCM,data:3SjZv/c9Ygx9RVgQ9UTm,iv:i8VWQ26KBFIhdmjkCrRNET4MsHDmVop3Rw1pOehW6uY=,tag:jJ0kMPh9+xVzhSvdWfet6g==,type:str]
    FRIGATE_RTSP_PASS: ENC[AES256_GCM,data:yp+ZNIvPuF/gqZ9h,iv:iSoJ7TdekoPIZx1qMDTmQwCx3Nkhee+mQ2rB/1lHcmQ=,tag:luVC2XgXqBuolDeDEzM09g==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:CUaDCu8wr/05uCTFyCZc2FCbpRWy3SCRlyQhaBsUYUHRws0/eP/hew==,iv:FpZd13iRQ4VTzsi8ztoVeynkP8pHvEDjUYsoMYTDAlU=,tag:bSaEQSBjI+xCg+xp7Bof+Q==,type:str]
    #ENC[AES256_GCM,data:lGitEtxIsfV2vdAe43tRTKo3q3JJySBYuyItoSZaipSMV8JdpjbG6wUinL24PZXmr5y0MGk+vsniCeaOAipQLcc=,iv:Tb66fuaBEcu4/3j1Dw3g5ZNi0AHmwShxq5IHQkJm1wg=,tag:o1p7Z21lsmmwN7JU1n+NuQ==,type:comment]
    #ENC[AES256_GCM,data:sHt/8pxWAAciPbyxgc3wYlbx5QVB7ZRlmAmPIXAwfJ0FxZG40pfklF2iu7w=,iv:A23Yq2xg174cI065ZnpqjGc35ekH2l39gNC9/7BeT3o=,tag:dt4sol+rVjhgNSvDfF85Ow==,type:comment]
    VIP: ENC[AES256_GCM,data:hSWURUx1PAsXECFh,iv:KMMtCiE27s3EvkgOWB2wCP1RQFV5XznszI6dy9Mdz10=,tag:pEIXmMFdW8TA9UFbELeJEA==,type:str]
    #ENC[AES256_GCM,data:mEn28tM0BQ2EmygSe7Wg80Zup1g165L42tU=,iv:0gDP6lusbFp65HhEJSGnPBA9O5oZzjIUO6Z/QPQ2T8U=,tag:ycFtm5LwL/uJvBQa6GUJUw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:JA4kVmd9Th3ejeTSbQ==,iv:pHyA9NMKJvP60jBjtQnYrLwtTKlQ+FVdkqB4nCP/hnA=,tag:UcQcIHkQWRIIzYbmpc1KkQ==,type:str]
    #ENC[AES256_GCM,data:K4+2V82lLOmQ2u/BksIYp+uPCPfZQm+DnJza7ArMxvYMGw==,iv:aDVGY4emuGWbyYkqWhfaEkutTCtDQVsaY4NnNjWX/ok=,tag:3yB39JK4JNayN+8cSNRfJQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:i3eHHNuIkTSL8XY=,iv:SanW6+RnPU624pnD7Xu35IwoQ/Q2fj2U/CtkGAXvk4M=,tag:lDGBujn3ncO2knIZvSAbzg==,type:str]
    #ENC[AES256_GCM,data:+CkTQOa57Ue9zqI3p53SPzEjsvjJpmplYje5gU3X9O1yvsEgD/a21z9qkX24dX0=,iv:ZO2cVi0NB5Z/NHshvSez5u1TaPpVjGHylkEaoXzZPo4=,tag:xJKH1/YO/CQtr73k+XETHA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:cswpaIo5Yf1IWY6uUh2uYIbzBiP5+gFMWQ==,iv:xPjXS9jH8daTJqKmJ5im6VoyYTWUygd/cPsXXV+GF1o=,tag:vOVnOkpX+HVGU7ARkGLj9Q==,type:str]
    #ENC[AES256_GCM,data:0NyjvebHBOF/kkwbPVRLct/RaUplVwVa5RDPeDwaK+5BV83qK86JV95gkNMBqM2oi0rs8Rd8dtQ73HKyUkjn/5goIFR6A7UVg8uLAJyjpyA=,iv:vEFCV/sQVC2YgWoTMlRMcj01b8z9M98SavG67rYISaQ=,tag:OhQiJJtoo0lmi8QvxMzV1g==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:lOgqK5KbyA3cWjt/,iv:RzoYk+4un3+K1GcLt8eh3Xhgiu6f5z+Lbgr+PCQDsR0=,tag:sOA0wGlYD4V8DOPyIbwPyw==,type:str]
    #ENC[AES256_GCM,data:KOXevTEblOaipfBaWm8W5GAUWcafFbrhrxnfYQZRBUF5kP4okCYOuIy0QKGSB37d1Al1FT5xd+0=,iv:1zQx3jTA18NmnlP1SOYz27ejYgSmPSfNyAAJyDrT/Bw=,tag:UaVvTx03O4X5izd9hf5hcg==,type:comment]
    #ENC[AES256_GCM,data:EsaXkF4ufx88NtYGP+HYgKYPmhGl46T3iw==,iv:STkaE1NU0HjEdTV9UhuCCl09GYYO0OzjOUQFl2O8pD8=,tag:yIkxpNxWHHsK9icYWZFS5A==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:8AKS1RRdFtVJDPcv1X4jNZHRgSkYrxYXqvHJSlf9btT2cuWOHemZaf/Jfu79pa5A,iv:yBH5qfvpQcH80QjRZzuqWCNz0Yp2V3jdkzfE9mfygSA=,tag:7vmnqNVO4UqD0lmP23TRYw==,type:str]
    #ENC[AES256_GCM,data:Pmqi3S8LloaZz3tbBg==,iv:jWKngKqinLcK4dG1NJQha7MkejNiWVNgDNFplysiTTY=,tag:A+qUNfr4R8yq37efb6O5zA==,type:comment]
    PODNET: ENC[AES256_GCM,data:F2e9CXHrUjWx9FJz3w==,iv:mzIECevj+mmclZdIU8z0rWFtoKD1z4pETgFv+gpYb8Q=,tag:m8Ijvc8Fwf6T+8njF3uqLg==,type:str]
    SVCNET: ENC[AES256_GCM,data:cQ+Seh9HmjWSbyg4KA==,iv:4poxUh7qcW6ca0pCNVGG+b9kp1j3tlkSMqWknJK3TsI=,tag:7haDKCqN5anQLARPu9hagA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:qq0ojA==,iv:C9FY1Jd4vEfP5KG381SumQtTRs3bGb/lUIpktB4Qf/4=,tag:AFwoTjdQherhJ0RuQpf/7w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSlRvNHNoNUJxZ0xmZkla
            K2x1ZWF3aGV5aUdlMDlVU3VucWl6UlhFcW1NCk5qUHk3eVFRQ3paMTFBaDlDVWdU
            aGtJd0FYWExqcTZkUlc1QzUyWWg5RDQKLS0tIGhFOEFSMGFTazZIVVlHN0ZYQVJR
            dWJPWVpTOTBub3FvMmpFa1poOXZNVGMKISjHa9xnR1PhLANfsHiyVnNapPXn5Kto
            YRwFO+s2+E+9tjSB7GvO1M9/gbSp/sD15Y2ILQxbzlRa5vGOk9JDdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T17:05:45Z"
    mac: ENC[AES256_GCM,data:q+FzBJka3Qb5DeX80NEm1tq+CVh6G6VTrY4ZEmfwu3RwverkqbOR0TcDYkwXcY6WTPg9vCo8j9JHPyhgTYNaTyr9A34Gqhd1lvrqtYWFMB8dAN7G5lw/cPLXTcwtHNbP+v+4uespOfOvt1hW2IidkB5bEMhBoDSufmnR1P9IQu4=,iv:cx425xyPs+lI7kvY5BIk4TOQ9+dyuZ/+CtBTqqbiv5w=,tag:vyafQEoHI2Oz2FSjYvr6Uw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
