apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WoAZ4ofq6U84mWznsB58+G7uOLVqgHNVytg63P/jsEcMr0Pte5CRJqskn0OFpcT9l4iUmRqRf2feuNOjum/8xerpOt1U/Psfo1kHPrXvRVDRn/dtJp41rbmHCEcojj536Qh0wAKpykulVhQWKVBcNxc7oZx4bwwUbRfbb/Z8S7PGHBg4J3nqrr4lXvZsQXB5TgtJUlC9iLsDdojzUdzhqSu6mqRSq38SU4UDJBbwtamOlFds44lepSXhj8tgZs+ImSWOwxtVlSw9aVKy1ng/aaS6FUa9BUU8SWeDAlC2ho6JvKttGZ/rSVEN8m+14eSOVYpLM6QtMFQVm8bepkxYM41eBB8IpptSqCMkInz1enEZVC+X2gif8z38FpgtG+kj,iv:fvWdwL5V++R/AjK5UJlKwzmHjqvRDAuZwxKIz8eUl5Y=,tag:LTlI1WcWy6K9umGe4rN0CA==,type:str]
    identity.pub: ENC[AES256_GCM,data:C04jQXUtkzktZioajICYmPgZq9Mbw9YNtqpH3Q6mX+4HzGlkCJDXYbsObfQajWfFO4T7Ex++JJiN3iFCgyz3Lpb5AwqhL1ywYgd2xKpNR/izNXTsGVo445L4XYIALZTaf36mAhDq7txJNTEgdqD4JrA05c5Pimse+aIqd+STC/9pjB1GP/8msDR/22NPsoXVkZgKmV5sVCP+vzHczkt0iw0zjb3nDo6vqfeSKa/UWXbu6Qrd5ttz0VAZM7DRpBZXNKHZEJZYUm+UXCsUNw==,iv:Es84KJC7KY1+9xvVO+Lz8WSMZuL2m7KNRx5yKkLUM1o=,tag:+a4J96AvqtQNgLRUwl2U4Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:xrK3hyyNNCEqpzh8fm9dYnJwWXSXsCmpG8EXLz/jNOGaRtXQysovxRa+CqoHFGCBU90rUAxWhmm1AtAYX3uO0ep5NWFSVXXetksISp7EddKZN6lkyG383wByTiB6DNGBRSlv3x8W+DTNK7QYsH9dR7mT/1f8WMRphhy10OEZdXdMDzFIi3qX1kKTfTTKrqrRa6D0K9R6sxChzaTjl7lRUnkKeLlgXO7WPRQG,iv:iOr33snhdsZvz5NJyNwporl2sjc2vP7/VtS1ALaFI8Y=,tag:QfHKJz2jjlmrM7V/WvuCgw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdjlVMWJHajB0eEgzT1pk
            Zlp1UDJydDhyMis2V0NvSnRmV1JmYm1PblhJCllNaWJUeE5MZWFzYTl2VHJpcmg4
            RjVCRlV4NzBiQmpQUzgrS0J5elBZMU0KLS0tIDFZOXpOYm1nWG9YWC9DY3ZiMXow
            akhDV1VVRVhEN2p5VElJbEJORGlvaDAKI3+xutvvBUk0aBIdry7rZqxuCpI2msko
            P5nWYFTdLjhR128450+RwIjbb+9CrKN0my7vtLNkYalTwGrbivviOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-25T19:00:58Z"
    mac: ENC[AES256_GCM,data:zf6JFjRLrhvHwLdwS8YfL8IGGMq1bBpcyEwRMdbPhViDEfJjzM12KwONf9CmIwczO0QIflSB6/SpXv/PUgWHRsCwThjrjjdK6w/UIgo8C9AHBT4QKxP0gZvyEEhOuyaq+BYVU05UPjMtvMPmbRF21ZE/24T3taZkOpDFqfvSRzs=,iv:PhJ8jeFBVE9Ig+ond9M5hn/HbaFsTKGMZbZuWGdpp14=,tag:GytUXtpSu6wX3xBBDZ5JDQ==,type:str]
    shamir_threshold: 3
    version: 3.13.1
