apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tPwltsznA2CVbx2MKx+YVtbjh1QPIx11sQ5HXhA6YQnq9M5y0R+F1hRpniKkPeiP91ueqLF5yHmp5OKmIYL58FMtYfuLl0OFdy+7ZyALqy1dRw74HiInaiUaIk4oZMavc88xlh0ntlpPRi8YMxf4JcZBeQbACxNK/zhf2xSc0ERAiB1nqw25FSC4R4AEHFDtEEDXFzm3r0GEMjv/TuWg86sH0ZB1IJcLiuiSg3XwUPegy1Ko+30RWI7jOodUh9UJ36FYqfYBrx4a9f2Sa2+rD9Rw2GIZcHJF49/z6KRakfMJyaCSKM6lrT+VLeQ0vjxWdu4lZwDE6vF6j50v1vlqhoApC2b/8IVncL1fftjvPgxZj3tX1qWGsPLAfo34CLX1,iv:nWaZEjfUJbpECu7RY40XvMbrfu9nq2zNOpDm7vTFWFo=,tag:3pmYDb2jzywLTjd17eHEzw==,type:str]
    identity.pub: ENC[AES256_GCM,data:UB7RpsA+8Q+n+KbizMbKn1CV0MGy/Esb39zrvZUoYZJVEOUrVIpxCQbJTDv2XLwBSWy0z4dhR2AaZhUzG1QOhbH9Lc5Tlva7oa9ru2TMAJBztoXtKAQAcu/xP6gBV54Gwj9DTjKxW8jRR7j3X8wRBfYemIF6ozz5eiiCi/oMJ7cVSNTUBWuAOCE/c4i8q2SdKA7QzzMJmaOlYGdDBhpIM3Tb88YckyfACm9LIP0qtzW4y/NShPz5ijx0x+nF44skZZJvHFarDqGRLOyuaA==,iv:RrgbcsTz90Dj+6IbyQ9QN0zNuM+eWsdRdH5sDKL7fzE=,tag:vAXBQotJ+dAfdu8MCVsROA==,type:str]
    known_hosts: ENC[AES256_GCM,data:F48OfgWgmP3/TM8gLWLf1CTttDyv7vQKnfI3WnWtew6/44qI/gb986y/7CmhDXWiaok4M2Dwg3zIfE05kCiuQ9RQI+HrxRuNhuaJRf2NZrLoPkGPoRbymcfmY+D01Zv/aRxyXnTBbnT5e/+xr2vy+YKM5q7j3zRnu59YxYf5zRCmItLFQRkEotmz7g17djaHqrQQA7CyE3Sl5XRChVN4jbKMeeWKxaYeoBa1,iv:JEoIwf9suIrN2PfYx04hjzfSi2BujsQ61lzEXCR6TNg=,tag:oo9B+gBK8y3LlgD1nzUryg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTVdYUHZKZTUrMUFVcm80
            eUJtUDY0bmFlK1MwaHZQSXRHbndXZzIyLzE0CjVCbkxFNHd2azNFWG5obEFEWitH
            Mk8rdDlLd1lvaUpHZFhMV0V1TWNJVk0KLS0tIEVMeHIyQ3AvRWRwRURCSldZTTE3
            UXRoMlFNUnFQYythKzNDNGdEYTJOM2MK3zvNs28oXODY4/km7tZ/6nEuATeQ2Bx7
            NPwYy68RjHKXnGvfKixjxBKaSD+pLm+m+bNOZKpsAUtbiPWlu5YENQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T04:07:25Z"
    mac: ENC[AES256_GCM,data:PM/oMgjbPrfWDer8F9IvdA1k1IZtwn0VSAESC8SjOwAvVWMQ/StnSyKhXrAU8yh0T5C++KfxV5OnWm6i6trkv5Ed9qah24Cfk1UVYABpW7Jr+PUb6DxftSxagMq62VvgZu0fqmRuGvlyTcpXCgLKQzGo/pBzc0QD5TF1Y6qcNtc=,iv:p8SnBnO7lJ78dfJve2Mc9itH7MZOTtHATRB5S5brbyk=,tag:a1oG6wXI6K8wUakXh68sng==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
