apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9Qd/Sqq/EVYsgU3/xGKZmmo/LbgVoedLzIKrJ1tDt/29bxuD8HyfxC7socMTQa9RASF2ANEzUlJtqt2+x3aJobI+5Y3PGmYagKnqYcY6m0auMHsXLojRH4WBAXxfCTCAdhVcuomcCfy3Ws3g97Wx/33mdA1C8qrj3Ru9OrGu4I8r2Pk/rkk4OCufK1L+HSXVqa9uxcIDOhYY0+KWlSqEBMmIwyQP0jFe+Z/Tlgg82q0M4YclxsN2lbbgNtZ5xmbXhNgqNHiyggG4kvkV+/npgO67eE5VVfEx97KAKFdaT/dMQVL/wJC0EcKqfSNv6Mh/1rn6e93jIWIUQ5ZP4I5nmcJzQ7p0KOwdCymBORxmp9oaKZyQp4dXfWU+wmLWWFUM,iv:EkUwRlFwIARHBGDH36XsOAGQn97WKCIndtBwpJN2bjo=,tag:iDdokC+NT4kwuTBfYH9pxA==,type:str]
    identity.pub: ENC[AES256_GCM,data:XfvRdMu4DaG+0krQBxZ8Ai5iu43g6caovK5WK5IszNCfPdtOK7uUdgVdq87ExP23v7bT/e/tNrcvnadVWt2pC9tY2YXY3Ykp6Sw0mGtIShs7xd6gBIGuxxzE+xZyFlBtkdqHPs/pSFwRYInK4a0FQjpmZXxlJRByHjeRRFa3UkIjb0GfOAY9DyAxq0FZd5ngZeC8/yiDR3IewR2UAxTmWj6pVzpFFCMOhj1UjnKo8KWc4k8je0qr9XlfbVyw1bVAklv6zpxoBV/FO+cPcg==,iv:PmmoD3unlzvYCn6CdtRW9uNseP5e5G7V+Dmwe7gJgN8=,tag:P+ElxtDWBmUG+2fl27MoMA==,type:str]
    known_hosts: ENC[AES256_GCM,data:xQFIApdBOkLUSE8Cq0cpowkSiORl0t74TQX1qNiLXkH2zOGxdeUWNz/gTI9jKkn2vxCmhbxV7CiBqfDglTGURaHCZ2xhDFJjCqyuE2Lqyx3Pn2q7dOifblAt3dMXWrY1PGjlps5Tv8SjxJoSi1hnPf8mlTIZ3qUU4/apBfaWNZ3uc+oNcJN2SxLlFSLa/v5ktUNxTrOAOidcuoQYFynfYrnd7MwKewe28c3j,iv:RzZag/i92inTjuWeVClLEcNI4ub9C5rCUM5x3ybEH1Y=,tag:7gZa/L9riCJZoNTcwVJ/nw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZEVwTlNhaXFzeVQ1d1hZ
            WDY4M0k3THZmaW5SUnJFbEVxUThZUU1RbUFnCktGL2tCUk9sb25BRWxLb0ZKb3NO
            TTExeEVidGFEekxUOTFZOGRBYUtIWEkKLS0tIGRQeVZjcE96cWw5NlN4Y3JLQWhn
            cjJRNWhiTzJGVXpNcHhvcjVJNDgyUFEKkRnsX0OD2JIEVHy9t2/64Vo3OT5E3dqg
            /SUWaYPDqKmDOGHFF4HbFDrSP3djY4s87skNC86TrtUU8HVAa/Iy2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T00:06:51Z"
    mac: ENC[AES256_GCM,data:M7Mwqbzp4//W0990rw/etAfBoiZvpOk9n7cr7J4NnxtK6BtEw7/RkTFf2Hcx4pNvNIRpfbMvvMkcXnbztBMBFmUw2bP9zzRNBVH/E3cFKHWzChmuPE+iNx62WL43Oswjrh6IFOQbIW2YDv9NGzs8kfAzo7W24eKef6Kq77IIFgE=,iv:WD4u3HqL5Vsowo1Uk6QEVBmYZtRFEphTxanXWk2X9JE=,tag:UFiGSSkBId8I6PpGhAPo0g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
