apiVersion: v1
kind: PersistentVolume
metadata:
  name: "prom-pv"
  namespace: kube-prometheus-stack
  labels:
    app.kubernetes.io/name: prom-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 75Gi
  storageClassName: miroir-local
