---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hass-external-service
  namespace: hass-external-service
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 16.3.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: hass.${INGRESS_URL}
            paths:
              - path: /
                pathType: Prefix
                overrideService:
                  name: main
                  port: 8123
        tls:
          - hosts:
              - hass.${INGRESS_URL}
            certificateIssuer: "domain-0-le-prod"
        integrations:
          certManager:
            enabled: true
            certificateIssuer: "domain-0-le-prod"
          homepage:
            enabled: false
    service:
      main:
        type: ExternalIP
        externalIP: "${HASS_EXTERNAL_IP}"
        useSlice: false
        ports:
          main:
            protocol: http
            port: 8123
            # Target port is the port of the "external service"
            # Defaults to "port" if not set
    workload:
      main:
        enabled: false
        podSpec:
          containers:
            main:
              env: {}
