apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatuscustom2
  namespace: gatuscustom2
spec:
  interval: 15m
  chart:
    spec:
      chart: charts/gatuscustom2
      version: 0.0.6
      sourceRef:
        kind: GitRepository
        name: cluster
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: LoadBalancer

    ingress:
      main:
        enabled: true
        hosts:
          - host: gatus2.${INGRESS_URL}
            paths:
              - path: /
                pathType: Prefix
                overrideService:
                  name: main
                  port: 80
        tls:
          - hosts:
              - gatus2.${INGRESS_URL}
            clusterIssuer: "domain-0-le-prod"
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          homepage:
            enabled: true
            group: Default

    addons:
      codeserver:
        enabled: true
        service:
          enabled: true
          type: LoadBalancer
        ingress:
          hosts:
            - host: cs.gatus2.${INGRESS_URL}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - cs.gatus2.${INGRESS_URL}
              certificateIssuer: "domain-0-le-prod"
          integrations:
            certManager:
              enabled: true
              certificateIssuer: "domain-0-le-prod"
