---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefox
  namespace: firefox
spec:
  interval: 15m
  chart:
    spec:
      chart: firefox
      version: 40.2.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: ${TZ}
    workload:
      main:
        podSpec:
          nodeSelector:
            ${INGRESS_URL}.node-restriction.kubernetes.io/camera-nic: "true"
        replicas: 1
    persistence:
      config:
        enabled: false
    route:
      main:
        enabled: true
        kind: HTTPRoute
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Tools
          gethomepage.dev/href: https://firefox.${DOMAIN_0}/
          gethomepage.dev/icon: https://trueforge.org/img/hotlink-ok/chart-icons/firefox.webp
          gethomepage.dev/name: Firefox
          gethomepage.dev/instance: "internal"
          gethomepage.dev/description: Used for browser access to cameras
        parentRefs:
          - name: envoy-internal
            namespace: envoy
            sectionName: https
        hostnames:
          - firefox.${DOMAIN_0}
