---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wg-easy
  namespace: wg-easy
spec:
  interval: 15m
  chart:
    spec:
      chart: wg-easy
      version: 16.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    securityContext:
      container:
        capabilities:
          add:
            - NET_ADMIN
            - NET_RAW
    ingress:
      main:
        enabled: true
        hosts:
          - host: "wg-easy.${INGRESS_URL}"
            paths:
              - overrideService:
                  name: "main"
                  port: 51821
                path: "/"
                pathType: "Prefix"
        integrations:
          certManager:
            certificateIssuer: "domain-0-le-prod"
            enabled: true
          homepage:
            enabled: true
            group: "Default"
            widget:
              custom:
                password: ${WG_EASY_PASSWORD}
        tls:
          - hosts:
              - "wg-easy.${INGRESS_URL}"
    service:
      vpn:
        type: LoadBalancer
        loadBalancerIP: ${WG_EASY_IP}
    workload:
      main:
        podSpec:
          securityContext:
            sysctls:
              - name: net.ipv4.ip_forward
                value: "1"
              - name: net.ipv4.conf.all.src_valid_mark
                value: "1"
          containers:
            main:
              probes:
                liveness:
                  type: tcp
                readiness:
                  type: tcp
                startup:
                  type: tcp
              env:
                WG_HOST: "${DDNS_URL}"
                PORT: "{{ .Values.service.main.ports.main.port }}"
                WG_PORT: "{{ .Values.service.vpn.ports.vpn.port }}"
                WG_MTU: 0
                WG_PERSISTENT_KEEPALIVE: 0
                WG_DEFAULT_ADDRESS: "10.8.0.x"
                WG_DEFAULT_DNS: "${BLOCKY_IP}"
                WG_ALLOWED_IPS: "0.0.0.0/0, ::/0"
                # PASSWORD_HASH uses bcrypt. You can create a hash at https://bcrypt.online/
                PASSWORD_HASH: "$2y$10$eWPQ2qKsNe8l9SWv0n36euEwZmHDATYeuDeQeAreTibFHxPZC6Cn."
                LANG: "en"
                UI_TRAFFIC_STATS: "false"
