---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wg-easy
  namespace: wg-easy
spec:
  interval: 15m
  chart:
    spec:
      chart: wg-easy
      version: 18.5.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      mys3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3BUCKETNAME}"
        accessKey: "${S3APIKEYID}"
        secretKey: "${S3APIKEY}"
        encrKey: "${S3KEY}"
    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            cleanupCachePVC: true
            credentials: mys3
            dest:
              enabled: true
            src:
              enabled: true
    securityContext:
      container:
        capabilities:
          add:
            - NET_ADMIN
            - NET_RAW
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          gethomepage.dev/instance: "internal"
        hosts:
          - host: "wg-easy.${INGRESS_URL}"
            paths:
              - overrideService:
                  name: "main"
                  port: 51821
                path: "/"
                pathType: "Prefix"
        integrations:
          certManager:
            certificateIssuer: "domain-0-le-prod"
            enabled: true
          homepage:
            enabled: true
            group: "Default"
            widget:
              version: 2
              custom:
                username: admin
                password: ${WG_EASY_PASSWORD}
        tls:
          - hosts:
              - "wg-easy.${INGRESS_URL}"
    service:
      vpn:
        type: LoadBalancer
        loadBalancerIP: ${WG_EASY_IP}
        integrations:
          metallb:
            enabled: true
    workload:
      main:
        podSpec:
          securityContext:
            sysctls:
              - name: net.ipv4.ip_forward
                value: "1"
              - name: net.ipv4.conf.all.src_valid_mark
                value: "1"
