---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trek
  namespace: trek
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 18.12.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: ${TZ}
    podOptions:
      hostUsers: true
    securityContext:
      container:
        PUID: 1000
        runAsUser: 1000
        runAsGroup: 1000
      pod:
        fsGroup: 1000
    image:
      repository: mauriceboe/trek
      tag: 3.1.4@sha256:815b19a45b264d1ddfd8f3df394308f9d6307b26de45378630ba8179bc7691ad
    workload:
      main:
        enabled: true
        primary: true
        type: Deployment
        replicas: 0
        podSpec:
          containers:
            main:
              command: ["dumb-init", "--"]
              args: ["node", "--import", "tsx", "src/index.ts"]
              enabled: true
              primary: true
              env:
                NODE_ENV: production
                PORT: 3000
                ENCRYPTION_KEY: temp3be5919fda2ddbe3c7e95dd2694cc79576ea92f4d153d607c00bf641a3d9 # generate with: openssl rand -hex 32
                LOG_LEVEL: info
                ALLOWED_ORIGINS: https://trek.${DOMAIN_0}
                APP_URL: https://trek.${DOMAIN_0}
                TRUST_PROXY: 1
                DEFAULT_LANGUAGE: en

    service:
      main:
        enabled: true
        ports:
          main:
            enabled: true
            protocol: http
            port: 3000
    persistence:
      db:
        enabled: true
        type: pvc
        mountPath: /app/data
      logs:
        enabled: true
        type: pvc
        mountPath: /app/data/logs
      uploads:
        enabled: true
        type: pvc
        mountPath: /app/uploads
