apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome
  namespace: esphome
spec:
  interval: 15m
  chart:
    spec:
      chart: esphome
      version: 21.11.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                ESPHOME_DASHBOARD_USE_PING: true
    credentials:
      mys3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3BUCKETNAME}"
        #path: "/esphome"
        accessKey: "${S3APIKEYID}"
        secretKey: "${S3APIKEY}"
        encrKey: "${S3KEY}"
    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            credentials: mys3
            dest:
              enabled: false
            src:
              enabled: true
    ingress:
      main:
        enabled: true
        hosts:
          - host: esphome.${INGRESS_URL}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - esphome.${INGRESS_URL}
        integrations:
          homepage:
            enabled: true
            group: Home Automation
            description: "A system to control your ESP8266/ESP32s"
