apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome
  namespace: esphome
spec:
  interval: 15m
  chart:
    spec:
      chart: esphome
      version: 23.5.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: ${TZ}
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                ESPHOME_DASHBOARD_USE_PING: true
    credentials:
      mys3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3BUCKETNAME}"
        #path: "/esphome"
        accessKey: "${S3APIKEYID}"
        secretKey: "${S3APIKEY}"
        encrKey: "${S3KEY}"
    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            credentials: mys3
            dest:
              enabled: true
            src:
              enabled: true
      cache: #caches platformio packages to prevent excess downloads. https://github.com/esphome/esphome/blob/dev/docker/docker_entrypoint.sh
        enabled: true
        mountPath: /cache
      build: #caches compiled code to not require rebuilds on restart
        enabled: true
        mountPath: /build
        type: emptyDir
      platformio:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          gethomepage.dev/instance: "internal"
        hosts:
          - host: esphome.${INGRESS_URL}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - esphome.${INGRESS_URL}
        integrations:
          traefik:
            enabled: false
          homepage:
            enabled: true
            group: Home Automation
            description: "A system to control your ESP8266/ESP32s"
    resources:
      limits:
        cpu: 4000m
        memory: 8Gi
      requests:
        cpu: 10m
        memory: 50Mi
