image:
  repository: triliumnext/notes
  pullPolicy: IfNotPresent
  tag: 0.92.6@sha256:15e76cd0b34ac1376e36c06b8bd1cb281ce4e1610b49dea50a2da9bfbeb369c9
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 10156
persistence:
  config:
    enabled: true
    mountPath: "/home/node"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 1000
