image:
  repository: triliumnext/notes
  pullPolicy: IfNotPresent
  tag: 0.93.0@sha256:846671ab2f0025b66d7bc9563e22b983f04b85c047aac6cdeb2d4e52c245c516
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 10156
persistence:
  config:
    enabled: true
    mountPath: "/home/node"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 1000
