image:
  repository: triliumnext/notes
  pullPolicy: IfNotPresent
  tag: 0.92.7@sha256:545c3f52e0da7b57700f657c1ed681e96ed47813aa0b4fd34cfe0a3c9072570f
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 10156
persistence:
  config:
    enabled: true
    mountPath: "/home/node"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 1000
