image:
  repository: triliumnext/notes
  pullPolicy: IfNotPresent
  tag: 0.91.5@sha256:e5507bf828099ec1893f6070e2516c5b1087d786e809a2e55c2197324bb46ccd
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 10156
persistence:
  config:
    enabled: true
    mountPath: "/home/node"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 1000
