apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: generic-device-plugin
  namespace: generic-device-plugin
spec:
  interval: 5m
  chart:
    spec:
      chart: generic-device-plugin
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    workload:
      main:
        type: DaemonSet
        podSpec:
          containers:
            main:
              args:
                - --log-level
                - "debug"
                - --device
                - |
                  name: zigbee
                  groups:
                    - count: 1
                      paths:
                       - path: /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_5a7595ca07deed11b2b6ed2d62c613ac-if00-port0
                - --device
                - |
                  name: usb
                  groups:
                    - usb:
                        - vendor: "10c4"
                          product: "ea60"
                - --device
                - |
                  name: serial
                  groups:
                    - paths:
                        - path: /dev/ttyUSB*
