---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: music-assistant
  namespace: music-assistant
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 15.7.7
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: ${TZ}
    image:
      repository: ghcr.io/music-assistant/server
      tag: 2.5.8
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${MUSIC_ASSISTANT_IP}
        integrations:
          metallb:
            enabled: true
        ports:
          main:
            port: 8095
            protocol: http
      stream:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${MUSIC_ASSISTANT_IP}
        integrations:
          metallb:
            enabled: true
        ports:
          stream:
            enabled: true
            port: 8097
            protocol: http
    securityContext:
      container:
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        privileged: true
        allowPrivilegeEscalation: true
        runAsUser: 0
        runAsGroup: 0
    workload:
      main:
        podSpec:
          hostNetwork: true
          nodeSelector:
            ${INGRESS_URL}/music-assistant: "true"
    persistence:
      data:
        enabled: true
        mountPath: /data
      media:
        enabled: true
        type: nfs
        mountPath: /media
        path: /mnt/MainPool/media
        server: 192.168.0.109
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          gethomepage.dev/instance: "internal"
        hosts:
          - host: music-assistant.${INGRESS_URL}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - music-assistant.${INGRESS_URL}
        integrations:
          traefik:
            enabled: false
          homepage:
            enabled: true
            group: Home Automation
            widget:
              enabled: false
