---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: music-assistant
  namespace: music-assistant
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 18.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: ${TZ}
    image:
      repository: ghcr.io/music-assistant/server
      tag: 2.8.8
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${MUSIC_ASSISTANT_IP}
        integrations:
          metallb:
            enabled: true
        ports:
          main:
            port: 8095
            protocol: http
      stream:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${MUSIC_ASSISTANT_IP}
        integrations:
          metallb:
            enabled: true
        ports:
          stream:
            enabled: true
            port: 8097
            protocol: http
    securityContext:
      container:
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        privileged: true
        allowPrivilegeEscalation: true
        runAsUser: 0
        runAsGroup: 0
    workload:
      main:
        podSpec:
          hostNetwork: true
          nodeSelector:
            ${INGRESS_URL}/music-assistant: "true"
    persistence:
      data:
        enabled: true
        mountPath: /data
      media:
        enabled: true
        type: nfs
        mountPath: /media
        path: /mnt/MainPool/media
        server: 192.168.0.109
    route:
      main:
        enabled: true
        kind: HTTPRoute
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home Automation
          gethomepage.dev/href: https://music-assistant.${DOMAIN_0}/
          gethomepage.dev/icon: https://raw.githubusercontent.com/music-assistant/frontend/a9b3ace45becb6b6d770e1910c32c63d84ae4e37/src/assets/icon.svg
          gethomepage.dev/name: music-assistant
          gethomepage.dev/instance: "internal"
          gethomepage.dev/description: Music Streamer Supporting Many Sources and Outputs
        parentRefs:
          - name: envoy-internal
            namespace: envoy
            sectionName: https
        hostnames:
          - music-assistant.${DOMAIN_0}
