---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubeapps
  namespace: uptime-kuma
spec:
  interval: 15m
  chart:
    spec:
      chart: uptime-kuma
      version: 5.1.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      tckubeapps:
        type: LoadBalancer
        loadBalancerIP: 192.168.0.52
        ports:
          tckubeapps:
            port: 80
