---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whisper
  namespace: whisper
spec:
  interval: 15m
  chart:
    spec:
      chart: wyoming-whisper
      version: 11.5.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: ${TZ}
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${WHISPER_IP}
        integrations:
          metallb:
            enabled: true
    route:
      main:
        enabled: true
        kind: HTTPRoute
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home Automation
          gethomepage.dev/href: https://whisper.${DOMAIN_0}/
          gethomepage.dev/icon: https://trueforge.org/img/hotlink-ok/chart-icons/wyoming-whisper.webp
          gethomepage.dev/name: Whisper
          gethomepage.dev/app: wyoming-whisper
          gethomepage.dev/instance: "internal"
          gethomepage.dev/description: STT backend for Home Assistant
          gatus.home-operations.com/endpoint: |-
            conditions: ["[CONNECTED] == true"]
            url: tcp://${WHISPER_IP}:10300
        parentRefs:
          - name: envoy-internal
            namespace: envoy
            sectionName: https
        hostnames:
          - whisper.${DOMAIN_0}
