image:
  repository: twinproduction/gatus
  pullPolicy: IfNotPresent
  tag: v5.13.1@sha256:977129a3cad3253906ef9c95d16a0f19a3ab5d3892404da809798b5b34bbd04d
service:
  main:
    ports:
      main:
        port: 80
        targetPort: 8080
persistence:
  data:
    enabled: true
    mountPath: /data
  config:
    enabled: true
    mountPath: /config/config.yaml
    subPath: config.yaml
    readOnly: true
    type: "configmap"
    objectName: config
# workload?
configmap:
  config:
    enabled: true
    data:
      config.yaml: |
        endpoints:
          - name: example
            url: https://example.org
            interval: 60s
            conditions:
              - "[STATUS] == 200"
              - "[BODY] == pat(*<h1>Example Domain</h1>*)"

cnpg:
  main:
    enabled: true
    user: gatus
    database: gatus
# Default values for gatuscustom.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
#serviceAccount:
