image:
  repository: twinproduction/gatus
  pullPolicy: IfNotPresent
  tag: v5.27.0@sha256:5091320d752756d7ac0a094d26ac38eb8216d7ed5857642b305522d1c6641f72
service:
  main:
    ports:
      main:
        port: 80
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: /config/config.yaml
    subPath: config.yaml
    readOnly: true
    type: "configmap"
    objectName: config
configmap:
  config:
    enabled: true
    data:
      config.yaml: |
        {{- if .Values.cnpg.main.enabled }}
        storage:
          type: postgres
          path: {{ (printf "%s?client_encoding=utf8" (.Values.cnpg.main.creds.std | trimAll "\"")) | quote }}
        {{- end }}

        endpoints:
          - name: example
            url: https://example.org
            interval: 60s
            conditions:
              - "[STATUS] == 200"
              - "[BODY] == pat(*<h1>Example Domain</h1>*)"

cnpg:
  main:
    enabled: true
    user: gatus
    database: gatus
