image:
  repository: twinproduction/gatus
  pullPolicy: IfNotPresent
  tag: v5.13.1@sha256:977129a3cad3253906ef9c95d16a0f19a3ab5d3892404da809798b5b34bbd04d
notes:
  header: testing
service:
  main:
    ports:
      main:
        port: 80
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: /data
# workload?
configmap:
  config:
    enabled: true
    data:
      config.yaml: ENC[AES256_GCM,data:ojiDyUjAS4sboBD3+FjT8rOf8YY3JG1puZQMa2kGJQj1nImClm+l2ZLfy3k5FhwhQ2yZenFl5+c0yhaQZBM3Qbu0Jmmj1Ub2bwOYWt6x5gnMugQC6nCTSF3MNCAIAthhu9sKe1UIMswAZync2q2ygPWyQrh+z8/pSmyAsmKqSabElOPzXa5zVW2nSXCudROzprUW6Pv0XnpA8TgroA==,iv:1TxDjvoGZfmfIzk2splf29xqwimeQQJcUnoChkJZo2I=,tag:rl2BqjgbsxH8t6TSajMHwg==,type:str]
# Default values for gatuscustom.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
#serviceAccount:
sops:
  shamir_threshold: 3
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1v0h4jwykmv73pklnjtfxzfa6uya3a7345d9gcs0xs582tw8ar3msg6fkt8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdThiNkhNUXNaU09mS2dU
        S2ZVT0FHRXRRN2d0TEJnazd0SVlmRTM2UnlVCldQdkU0ellDUDBSUjJUMXBKaFFh
        RlEzcE5NY2FQWFdYRFMrZDBaMW5YbmsKLS0tIHEyMm9sbXJpRkpxWWd4aFJiUlBr
        OE5KSUFJZmJCTU90VlNkWk90VnJYd3MKKNzOlX7OwNMXF5J32T0PCylnUCwAUlj9
        wU1dJBrim3pV/q+Kxg6fRsSxFrwf2dm80X0O/66C/8bA3AQH7eoPWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-25T04:09:31Z"
  mac: ENC[AES256_GCM,data:ayU6A8I6lHqZQ6fZLNRl+zoJALJuEnYrxYgXye3nzzJChi/Y/dqi82XBiX90r8OUAZ//IIctGnQkQoZWNwKfJsxkb50GwgijMdPjP8ojIQmUG63Z3D222eaJJB4gYQV+4akauXaJ8drhJyUvqdGl1NqXmGDGtL5nWm5P9a6+fcc=,iv:Jk1KaBwFmON+15OkUfLzPQKRnUUNPg81DkTg2qkC9/4=,tag:4Uz0gehwjsEsJwz3inATeQ==,type:str]
  pgp: []
  encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.9.1
