---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valetudo-external-service
  namespace: valetudo-external-service
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 17.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    route:
      main:
        enabled: true
        kind: HTTPRoute
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home Automation
          gethomepage.dev/href: https://valetudo.${DOMAIN_0}/
          gethomepage.dev/icon: https://raw.githubusercontent.com/Hypfer/Valetudo/99a91f68b0148bc888a93615c6a5b7e7cd95577b/assets/logo/valetudo_icon.svg
          gethomepage.dev/name: Valetudo
          gethomepage.dev/instance: "internal"
          gethomepage.dev/description: Cloud Free Web UI for the Dreame X40
        parentRefs:
          - name: envoy-internal
            namespace: envoy
            sectionName: https
        hostnames:
          - valetudo.${DOMAIN_0}
    service:
      main:
        type: ExternalIP
        externalIP: "192.168.0.208"
        useSlice: false
        ports:
          main:
            protocol: http
            port: 80
            # Target port is the port of the "external service"
            # Defaults to "port" if not set
    workload:
      main:
        enabled: false
        podSpec:
          containers:
            main:
              env: {}
