apiVersion: miroir.home-operations.com/v1alpha1
kind: MiroirNodeGroup
metadata:
  name: std
spec:
  nodeSelector:
    matchLabels:
      storage.miroir.home-operations.com/class: std
  template:
    pools:
      - name: default
        loopfile:
          baseDir: /var/lib/miroir
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: miroir-local
provisioner: miroir.home-operations.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  miroir.home-operations.com/replicas: "1"
  csi.storage.k8s.io/fstype: ext4
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: miroir-snap
driver: miroir.home-operations.com
deletionPolicy: Delete
