---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome-external-service
  namespace: esphome
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 15.2.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      main:
        enabled: true
        annotations:
          traefik.frontend.passHostHeader: "false"
        hosts:
          - host: esphome.${INGRESS_URL}
            paths:
              - path: /
                pathType: Prefix
                overrideService:
                  name: main
                  port: 6052
        tls:
          - hosts:
              - esphome.${INGRESS_URL}
            certificateIssuer: "cfcert"
        integrations:
          certManager:
            enabled: true
            certificateIssuer: "cfcert"
          homepage:
            enabled: true
            group: Home Automation
            icon: https://esphome.${INGRESS_URL}/static/images/favicon.ico?hash=2655a073
            widget:
              type: esphome
    service:
      main:
        type: ExternalIP
        externalIP: "${HASS_EXTERNAL_IP}"
        useSlice: false
        ports:
          main:
            protocol: http
            port: 6052
            # Target port is the port of the "external service"
            # Defaults to "port" if not set
    workload:
      main:
        enabled: false
        podSpec:
          containers:
            main:
              env: {}
