---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 15m
  chart:
    spec:
      chart: authelia
      version: 27.1.10
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: auth.${INGRESS_URL}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - auth.${INGRESS_URL}
        integrations:
          traefik:
            enabled: false
          homepage:
            enabled: true
            group: Default
            widget:
              enabled: false
    workload:
      main:
        replicas: 1
        strategy: Recreate
        podSpec:
          containers:
            main:
              env:
                # Update the following secrets with your own values
                AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_SECRET}
                AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ${AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET}
                AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
                X_AUTHELIA_CONFIG_FILTERS: "template"
    credentials:
      mys3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3BUCKETNAME}"
        accessKey: "${S3APIKEYID}"
        secretKey: "${S3APIKEY}"
        encrKey: "${S3KEY}"
    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            cleanupCachePVC: true
            credentials: mys3
            dest:
              enabled: true
            src:
              enabled: true
      private-key:
        enabled: true
        mountPath: /opt/mg/private.pem
        subPath: private.pem
        readOnly: true
        type: secret
        objectName: private-pem-secret
    cnpg:
      main:
        #mode: recovery
        backups:
          enabled: true
          revision: "1"
          credentials: mys3
        recovery:
          #revision: "1"
          credentials: mys3
    secret:
      private-pem-secret:
        enabled: true
        data:
          private.pem: |
            {{ genPrivateKey "rsa" | nindent 2 | trim }}
      test-secret:
        enabled: true
        data:
          private.pem: |
            random stuff
            multi-line string
            hello2
    # All configuration options should be put under this. Supports all upstream options
    authelia:
      session:
        # Be sure to change this to your domain. You can also define multiple domains
        cookies:
          - domain: ${INGRESS_URL}
            authelia_url: https://auth.${INGRESS_URL}
      authentication_backend:
        # lldap setup
        # https://github.com/lldap/lldap/blob/main/example_configs/authelia_config.yml
        ldap:
          implementation: lldap
          address: ldap://lldap-ldap.lldap.svc.cluster.local:3890
          base_dn: dc=${BASE_DN},dc=xyz
          user: uid=manager,ou=people,dc=${BASE_DN},dc=xyz
          # user with lldap_password_manager group
          # above user password in plain text
          password: ${LLDAP_MANAGER_PASS}
      notifier:
        disable_startup_check: true
        # smtp setup (example is gmail)
        smtp:
          address: submission://smtp.gmail.com:587
          # gmail email address (username)
          username: email@gmail.com
          # use a google app password if using gmail
          password: somepassword
          # email address to show as sender
          sender: no-reply@example.com
          tls:
            server_name: smtp.gmail.com
            minimum_version: TLS1.2
            skip_verify: false
      access_control:
        default_policy: "deny"
        rules:
          # basic rule for one factor (username/password) login for users in the admin group
          - domain:
              - "*.${INGRESS_URL}"
              - ${INGRESS_URL}
            policy: one_factor
            subject: "group:lldap_strict_readonly"
          # basic rule for one factor (username/password) login for users in the admin group
          - domain:
              - "*.${INGRESS_URL}"
              - ${INGRESS_URL}
            policy: one_factor
            subject: "group:admin"
      log:
        level: "trace"
      identity_providers:
        oidc:
          cors:
            endpoints: ["authorization", "token", "revocation", "introspection"]
            allowed_origins_from_client_redirect_uris: true
          hmac_secret: "${AUTHELIA_HMAC_SECRET}"
          jwks:
            - algorithm: "RS256"
              use: "sig"
              key: |
                -----BEGIN RSA PRIVATE KEY-----
                MIIJKwIBAAKCAgEAzoIrAkTXGDQfAmP1dJ880moALsPAcdE5XJqD6ykurzgRbKts
                d7C9iw3tbeCp/Zagms49ltmvKt45Vcisg2hXZLQWPnjX8owtrN9SitXuN3be61LT
                VwXfdVvMZ2bFKu6m1NoMfcqg9nMWnKwkq2WU0YiPISmuErtUUhkbZqakeGc9Yw48
                y5ZF+oajfPkJZy7XmFlt5TSxijnzQMc5545s5gb1RLu/BO4Ob/DR8p78ex0E7TUf
                LphifMBJK4WslPsbJDRhHJ0Cq368SR/VC0onNDUuVRnb1bwqB1Qf3bXPeTK0zpwv
                5aBl5DEMnV6PWpyeiWav93u2Nbcmuj4V/hDN9FcJJP9M4JQRJCfLtJQz16VS/7py
                01R8b2w9VAuqWdRdxO01JvicHTaMIzutHYqdZWGurz9TBMHhnOVOD0fLd2DGrbPC
                JomxiMT8jeplh38GQ61fhr8HxGs7TqM8CUq+2b0L/ibj32eZpSJdP7gaschtvCkT
                hKaaORERZ65n2p1vCSJP+dvrZ9JT+t7QylQSTJ+xiAslEv4q/j6+KbgXMUZMz6eA
                itNBFOcSWx3UHFW1S78KApYi5Pb7jN2DROWkAR2iyWxW9m5/+ge/D+dHsolw9XmB
                Im5O/tP510KEmqiSUzSbrg7cMd/fNiQg7dZkF3b7yNaReAk3S22WMjBXYbUCAwEA
                AQKCAgEAtrZC2WoRKbAL87B/XyT4ym7RJI87+TgV2ZI4v9sbHBquiAiQGsI8ogi7
                lukdXmpkRTPPGGYX7wTZk8XOpSGvmUEhITsITeirDPY2cPJhJ5+8Eleg97ERiiOj
                kaVDM/4di9w1CyM6EXO4gPxqIV/qMQ3zHXNkOdyW+WCPdt5gTMuDa94P+k1GMyfn
                BM7O/AVc6cXOTuq1XshxKlJbMD46qbdkUOEQXItIKNDY4SK73y3IyxuiMDbRhPEY
                jDJkhRg7ZmgVuBxPXW7vpn9MnwWH9FBNYyxS7iPix8Mtwpt3KxOrF9bnJfMp06F2
                ONKOYayLNKSvcnd5usMGt+fwy28Q2NUCie9AAUfDLbzhEGvvY6njzHors8l4OflZ
                +YMC3ZWWNTyMp7cnCVk6OnEIl89Cy5Sn34nE+TEOK7L13XvevSuauKKcY50ACSYG
                u6sAiwevXyNzBH2D62LL4GB3aCLSF+w6bU5m11dRNiyh5+2v3SJV+1+NnauEEEYc
                +oWYGxsDgQCpXgiVtuvEKMW86Z0UAet94VzyIeO6EnX3y1g31nBWTpxioR1YAPFr
                OELm1CHQTH6E8h0E3Hfd5n3k7CbRNzhAhCKeRd6iPFx377qb7zn507nsu9KxgOUK
                hU7ieFX1ZY1ujJKR4LNWpLmo2+DWp2qvtVawxHyAxLal4Ag9ui0CggEBAN4/grra
                yanXAz+P/zCBh9e9radboG10Sxg2FlTFa+Ub7kNHLS0ks1CWzs4VYM9AzcKKnMJk
                VB89kwX7JfpYKQxVx9LYaNqOHJQ8hyokMmF9HUFbTPlNeKz9c8CtvmeOJwdCF/xH
                3xRWs7uxWDiF8etXGUMP/5WhUkHrTivQ3Lt8jw5eJ6UGdT/WScFC5J7Bw6X5vsfE
                aHtrcdilPPQVxztdLdJyAso3yvpTAxJrO0gWwH2SBM+/HPZ5dIna7D0r2T7q9y2K
                DiO9qzAopv7V8JPL+YH/kE8b9VZAwVgzPBQ3iRCLrK+adcM5PmC6DE1niByACJMi
                m67dlSX/zMjKnNsCggEBAO3evMwyQ86ZzWliWwZJQpejurVrDCbeBqBc3EpFnkhj
                BZ9CWTGMt8owtAuseZFwcCeQlyiMJzmJiEn9mX6z014z8b6T93OrtgRGSlF+DQph
                yYzXQoQZEBk+2h6jvxeKoITnq8ncHtlyU4hSYDIWLJAXaQQuWRxR4HAJabs7DDDd
                qQ52y8FugqEijU5t015gmv2YWRthabRb6U54z7ukkLQar9Q2YyBmTAP+6n3pHpy6
                Pw8mVrWmAM0jh6r99MRUlH0S+GYJ3v6dOhoh7gCrrGpBgz3UYOA0pDpOGxQ4kd2s
                tfzJbHyZ0gWzzvEDsDMVM/i8dwx9HIOUlG7TJ+ZG+K8CggEBAIC9U3H/yK98YGJS
                fGVRsynSsyPt3KlqoxFcS2VBkvV9T3Bja5Tp3IFDSnpwQcrsZARcHOAyE9Sg62ic
                iexRYz3E9uJ4/4wSpBVuVnGf1BtKyUaRp64GJXA3xPSI8HG2E3+N1q0JyPxUGPsR
                iOP9GxzTMEv7mXbIowiSUI7rBuIIDiopeleKvSKEc+biY+JepYGggNXhPRC5NZJk
                bUGK2ATYPfHYnysaVJbavT3PJeDlZQ2YJvdcYl+YDVzJluz8WHSs0Q/tF7G2bdKQ
                yeN2dEx47IhUTPi2XlBfZGA+FYA0h04xSo/SLoMuxqZrPzMbVOoFdHIeqwYJTxta
                6Poq+98CggEBANReazLnoZA/0pvG2zuWhqS54gT8qKG+0i20Gl0ZIMLB3ZAdfWJ2
                ntQefXB6sSK/PvKj7cCeuJpvBsYAa10qkYhmWetrUZ7s7BmO4+Uz49KkEXzz5ofn
                lG7lpXl7ei07cCqYZ9BV/RjoMFniKc4t6+VNcU3xT0+wbe+5B7PIeQ7bp4apWyq8
                TlYscfpWpUJ6f4Xv0YZXhzcmY/rSc6y0tRiHRvnxALk5e56JpbN6QQFuasRM11df
                +REtKn/oMfJjDRtJp4n6QCQUHX6dUk849jr7eH/oMAGcHg+MEjMQenJuMyCYeIoa
                Dt9WdGjLgTFqObdWE/eLb7yuF4OGc/Xs4TMCggEBAIo4OSSYl/T0HbFko6uLu9ls
                /RmbtU8O6v0lfkq7OKM4bm/D7eAoWeq8+OANFFlwhX/3SjpEc/D2XswuWS+7Is/2
                xmXWETCbyYjbdCbY84u67IfXuNYFzEggkY5S5wsc041p+YWTRRNzgDvTL5cHEvLz
                qDe5/3B2gZCSccvN323iRTpT4xK2OkM5o844iBIrkF1N4m9JlR5cCiTLWnKSmRR9
                WYq+oE/h91HLWh6NTS2gUkoOqPFHaxIb9ruYRkIPkv8Z79RzG4cEDg6axTe4vo52
                eIhkbrvETTXpNmuirMWjpcqbvdIO0zBAuflWzgkPvkPnSkCm/cFVeZtOVz131mo=
                -----END RSA PRIVATE KEY-----
          clients:
            - client_id: ${OUTLINE_OIDC_CLIENT_ID}
              client_name: "Outline"
              client_secret: "${OUTLINE_HASHED_OIDC_CLIENT_SECRET}"
              public: false
              authorization_policy: "one_factor"
              redirect_uris:
                - "https://outline.${DOMAIN_0}/auth/oidc.callback"
              scopes:
                - "openid"
                - "offline_access"
                - "profile"
                - "email"
              userinfo_signed_response_alg: "none"
              token_endpoint_auth_method: "client_secret_post"
