---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 15m
  chart:
    spec:
      chart: authelia
      version: 27.1.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: auth.${INGRESS_URL}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - auth.${INGRESS_URL}
        integrations:
          traefik:
            enabled: false
          homepage:
            enabled: true
            group: Default
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                # Update the following secrets with your own values
                AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_SECRET}
                AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ${AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET}
                AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
    credentials:
      mys3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3BUCKETNAME}"
        accessKey: "${S3APIKEYID}"
        secretKey: "${S3APIKEY}"
        encrKey: "${S3KEY}"
    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            cleanupCachePVC: true
            credentials: mys3
            dest:
              enabled: true
            src:
              enabled: true
    cnpg:
      main:
        #mode: recovery
        backups:
          enabled: true
          revision: "1"
          credentials: mys3
        recovery:
          #revision: "1"
          credentials: mys3
    # All configuration options should be put under this. Supports all upstream options
    authelia:
      session:
        # Be sure to change this to your domain. You can also define multiple domains
        cookies:
          - domain: ${INGRESS_URL}
            authelia_url: https://auth.${INGRESS_URL}
      authentication_backend:
        # lldap setup
        # https://github.com/lldap/lldap/blob/main/example_configs/authelia_config.yml
        ldap:
          implementation: lldap
          address: ldap://lldap-ldap.lldap.svc.cluster.local:3890
          base_dn: dc=${BASE_DN},dc=xyz
          user: uid=manager,ou=people,dc=${BASE_DN},dc=xyz
          # user with lldap_password_manager group
          # above user password in plain text
          password: ${LLDAP_MANAGER_PASS}
      notifier:
        disable_startup_check: true
        # smtp setup (example is gmail)
        smtp:
          address: submission://smtp.gmail.com:587
          # gmail email address (username)
          username: email@gmail.com
          # use a google app password if using gmail
          password: somepassword
          # email address to show as sender
          sender: no-reply@example.com
          tls:
            server_name: smtp.gmail.com
            minimum_version: TLS1.2
            skip_verify: false
      access_control:
        rules:
          # basic rule for one factor (username/password) login for users in the admin group
          - domain:
              - "*.${INGRESS_URL}"
              - ${INGRESS_URL}
            policy: one_factor
            subject: "group:admin"
