---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: authelia-securitypolicy
  namespace: authelia
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: filebrowser
  to:
    - group: ""
      kind: Service
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: authelia-httproute
  namespace: authelia
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: filebrowser
  to:
    - group: ""
      kind: Service
