---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: satisfactory
  namespace: satisfactory
spec:
  interval: 15m
  chart:
    spec:
      chart: satisfactory
      version: 12.3.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${SATISFACTORY_IP}
    persistence:
      config:
        enabled: false
        mountPath: "/config"
      backups:
        enabled: true
        mountPath: "/config/backups"
      saved:
        enabled: true
        mountPath: "/config/saved"
      gamefiles:
        enabled: true
        mountPath: "/config/gamefiles"
      logs:
        enabled: true
        mountPath: "/config/logs"
      lostfound:
        enabled: true
        mountPath: "/config/lost+found"
    resources:
      limits:
        memory: 10Gi
