---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflareddns
  namespace: cloudflareddns
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudflareddns
      version: 14.9.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    securityContext:
      container:
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        runAsUser: 0
        runAsGroup: 0
    image:
      repository: ghcr.io/hotio/cloudflareddns
      pullPolicy: IfNotPresent
      tag: latest@sha256:0ccd6988c1abd1c8e5f99697791f25fcf63b6660d381b459407120f80790d44c
    TZ: ${TZ}
    cloudflareddns:
      api_token: ${DOMAIN_0_CLOUDFLARE_TOKEN}
      host_zone_record:
        - domain: ${DOMAIN_0}
          record: A
          zone: ${DOMAIN_0}
