---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clusterissuer
  namespace: clusterissuer
spec:
  interval: 15m
  chart:
    spec:
      chart: clusterissuer
      version: 9.2.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  #  targetNamespace: jellyfin
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    clusterIssuer:
      ACME:
        - cfapitoken: "-WMRmwTu7PUf4k9y6oBBBT7OxQDPcj4LEp1b5DpA"
          email: "mgale456@gmail.com"
          name: "cfcert"
          server: "https://acme-v02.api.letsencrypt.org/directory"
          type: "cloudflare"
