# https://truecharts.org/clustertool/csi/longhorn/#issues-with-longhorn-and-volsync
# https://longhorn.io/docs/1.8.0/snapshots-and-backups/scheduling-backups-and-snapshots/#using-the-manifest
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: trim
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 0 23 * * *
  groups:
    - default
  name: trim
  retain: 0
  task: filesystem-trim
