---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  interval: 15m
  chart:
    spec:
      chart: minecraft
      version: 11.15.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${MINECRAFT_IP}
    ingress:
      main:
        enabled: true
        hosts:
          - host: minecraft.${INGRESS_URL}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - minecraft.${INGRESS_URL}
        integrations:
          homepage:
            enabled: true
            group: Default
    workload:
      main:
        podSpec:
          containers:
            main:
              imageSelector: j21Image
              probes:
                liveness:
                  enabled: true
                  type: exec
                  command:
                    - mc-health
                readiness:
                  enabled: true
                  type: exec
                  command:
                    - mc-health
                startup:
                  enabled: true
                  type: exec
                  command:
                    - mc-health
              env:
                SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
                QUERY_PORT: "{{ .Values.service.main.ports.query.port }}"
                RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
                ENABLE_QUERY: "true"
                EULA: "TRUE"
                GUI: "FALSE"
                OVERRIDE_SERVER_PROPERTIES: true
                VERSION: "LATEST"
                TYPE: "FTBA"
                DIFFICULTY: easy
                MAX_PLAYERS: 20
                MAX_WORLD_SIZE: 10000
                ALLOW_NETHER: true
                ANNOUNCE_PLAYER_ACHIEVEMENTS: true
                ENABLE_COMMAND_BLOCK: false
                FORCE_GAMEMODE: false
                GENERATE_STRUCTURES: true
                HARDCORE: false
                MAX_BUILD_HEIGHT: 256
                MAX_TICK_TIME: 60000
                SPAWN_ANIMALS: true
                SPAWN_MONSTERS: true
                SPAWN_NPCS: true
                VIEW_DISTANCE: 16
                MODE: survival
                MOTD: "Welcome to Minecraft on Michael's Server!"
                PVP: false
                LEVEL_TYPE: DEFAULT
                LEVEL: world
                ONLINE_MODE: true
                MEMORY: 8192M
                RCON_PASSWORD: "${RCON_PASSWORD}"
                FTB_MODPACK_ID: "100"
                FTB_MODPACK_VERSION_ID: "12632"

            mcbackup:
              enabled: false

    persistence:
      data:
        enabled: true
        targetSelector:
          main:
            main:
              mountPath: /data
        volsync:
          - name: b2
            type: restic
            credentials: mys3
            dest:
              enabled: true
            src:
              enabled: true
    credentials:
      mys3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3BUCKETNAME}"
        #path: "/esphome"
        accessKey: "${S3APIKEYID}"
        secretKey: "${S3APIKEY}"
        encrKey: "${S3KEY}"
