---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: code-server
  namespace: code-server
spec:
  interval: 15m
  chart:
    spec:
      chart: code-server
      version: 14.24.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      meg-files:
        enabled: true
        mountPath: /meg/files
        volsync:
          - name: b2
            type: restic
            credentials: mys3
            dest:
              enabled: true
            src:
              enabled: true
    credentials:
      mys3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3BUCKETNAME}"
        accessKey: "${S3APIKEYID}"
        secretKey: "${S3APIKEY}"
        encrKey: "${S3KEY}"
    resources:
      limits:
        cpu: 4000m
        memory: 8Gi
      requests:
        cpu: 10m
        memory: 3Gi
