---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: konflate
  namespace: konflate
spec:
  chartRef:
    kind: OCIRepository
    name: konflate
  interval: 1h
  values:
    config:
      repo: github://mgale456/ClusterTesting
      statusChecks: true
      prComments: true
      publicUrl: https://konflate.${INGRESS_URL}
      mcp: false
      appClientId: ${KONFLATE_APP_CLIENT_ID}
    secret:
      webhookSecret: "${KONFLATE_WEBHOOK_SECRET}"
      appPrivateKey: "${KONFLATE_APP_PRIVATE_KEY}"
    httpRoute:
      enabled: true
      hostnames:
        - konflate.${INGRESS_URL}
      parentRefs:
        - name: envoy-external
          namespace: envoy
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 2000m
        memory: 2Gi
