---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 18.14.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/home-operations/home-assistant
      pullPolicy: IfNotPresent
      tag: "2026.7.1"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${HOME_ASSISTANT_IP}
        integrations:
          metallb:
            enabled: true
        ports:
          main:
            port: 8123
            targetPort: 8123
    route:
      hass:
        enabled: true
        kind: HTTPRoute
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home Automation
          gethomepage.dev/href: https://home-assistant.${DOMAIN_0}/
          gethomepage.dev/icon: https://trueforge.org/img/hotlink-ok/chart-icons/home-assistant.webp
          gethomepage.dev/name: Home Assistant (k8s)
          gethomepage.dev/instance: "internal"
          gethomepage.dev/description: Smart Home Automation Platform
        parentRefs:
          - name: envoy-internal
            namespace: envoy
            sectionName: https
        hostnames:
          - home-assistant.${DOMAIN_0}
        rules:
          - backendRefs:
              - name: home-assistant-app-template
      z-cs: # needs to sort after main so that main is really treated as main for the assumed backend refs above
        enabled: true
        kind: HTTPRoute
        parentRefs:
          - name: envoy-internal
            namespace: envoy
            sectionName: https

        hostnames:
          - cs-home-assistant.${DOMAIN_0}
        rules:
          - backendRefs:
              - group: ""
                kind: Service
                name: home-assistant-app-template-codeserver
                port: 12321

    workload:
      main:
        podSpec:
          nodeSelector:
            feature.node.kubernetes.io/usb-ff_10c4_ea60.present: "true" # zigbee dongle
          containers:
            main:
              env:
                VENV_FOLDER: "/mgale/.venv"
              resources:
                limits:
                  devic.es/zigbee: 1
    persistence:
      config:
        enabled: true
        mountPath: /config
        targetSelector:
          main:
            main: {}
            codeserver:
              mountPath: /config/workspace
      venv-cache:
        enabled: true
        mountPath: /mgale/.venv
        targetSelectAll: true
      backups:
        enabled: true
        type: nfs
        mountPath: /config/backups
        path: /mnt/MainPool/Michael/Backups/HomeAssistant
        server: ${TRUENAS_EXTERNAL_IP}

    securityContext:
      container:
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        runAsUser: 0
        runAsGroup: 0
    addons:
      codeserver:
        # -- Enable running a code-server container in the pod
        enabled: true
