---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  interval: 15m
  chart:
    spec:
      chart: zigbee2mqtt
      version: 16.6.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    route:
      main:
        enabled: true
        kind: HTTPRoute
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home Automation
          gethomepage.dev/href: https://home-assistant.${DOMAIN_0}/
          gethomepage.dev/icon: https://trueforge.org/img/hotlink-ok/chart-icons/home-assistant.webp
          gethomepage.dev/name: Home Assistant (k8s)
          gethomepage.dev/instance: "internal"
          gethomepage.dev/description: Smart Home Automation Platform
        parentRefs:
          - name: envoy-internal
            namespace: envoy
            sectionName: https
        hostnames:
          - home-assistant.${DOMAIN_0}

    workload:
      main:
        podSpec:
          nodeSelector:
            feature.node.kubernetes.io/usb-ff_10c4_ea60.present: "true" # zigbee dongle
          containers:
            main:
              env:
                # User defined
                USE_CUSTOM_CONFIG_FILE: false
                # This values are required for the autogenerated file to work.
                ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: false
                ZIGBEE2MQTT_CONFIG_MQTT_SERVER: "mqtt://mosquitto.mosquitto.svc.cluster.local"
                ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: "zigbee2mqtt"
                ZIGBEE2MQTT_CONFIG_SERIAL_PORT: "/dev/zigbee"
                ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: "ember"
                ZIGBEE2MQTT_CONFIG_MQTT_USER: "frigate"
                ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: "SHDdsbcnNqfc4zKdN9y"
              resources:
                limits:
                  devic.es/zigbee: 1
