---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chrony
  namespace: chrony
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 18.14.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: ${TZ}
    image:
      repository: simonrupf/chronyd
      pullPolicy: IfNotPresent
      tag: 0.9.1@sha256:8ccd8102f09b30246d8f3886a1d4f06052983690907d5b1e30dd723816ed29fc
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${CHRONY_IP}
        integrations:
          metallb:
            enabled: true
        ports:
          main:
            port: 123
            protocol: udp
    ingress:
      main:
        enabled: false
        integrations:
          homepage:
            enabled: true
            group: Default
            widget:
              enabled: false
    securityContext:
      container:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        privileged: true
    workload:
      main:
        podSpec:
          containers:
            main:
              probes:
                liveness:
                  enabled: false
                readiness:
                  enabled: false
                startup:
                  enabled: false
