apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: topolvm
  namespace: topolvm-system
spec:
  interval: 5m
  releaseName: topolvm
  chart:
    spec:
      chart: topolvm
      version: 15.3.0
      sourceRef:
        kind: HelmRepository
        name: topolvm
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    # lvmd service
    lvmd:
      managed: false
      env:
        - name: LVM_SYSTEM_DIR
          value: /tmp
      # lvmd.deviceClasses -- Specify the device-class settings.
      deviceClasses:
        - name: main
          volume-group: michaelvg
          spare-gb: 10
        - name: main-thin
          volume-group: michaelvg
          default: true
          spare-gb: 10
          type: thin
          thin-pool:
            name: michaelthinpool
            overprovision-ratio: 50.0
    node:
      lvmdEmbedded: true

    # storageClasses -- Whether to create storageclass(es)
    # ref: https://kubernetes.io/docs/concepts/storage/storage-classes/
    storageClasses:
      - name: topolvm-thin-provisioner # Defines name of storage class.
        storageClass:
          # Supported filesystems are: ext4, xfs, and btrfs.
          fsType: xfs
          # reclaimPolicy
          reclaimPolicy: # Delete
          # Additional annotations
          annotations: {}
          # Default storage class for dynamic volume provisioning
          # ref: https://kubernetes.io/docs/concepts/storage/dynamic-provisioning
          isDefaultClass: false
          # volumeBindingMode can be either WaitForFirstConsumer or Immediate. WaitForFirstConsumer is recommended because TopoLVM cannot schedule pods wisely if volumeBindingMode is Immediate.
          volumeBindingMode: WaitForFirstConsumer
          # enables CSI drivers to expand volumes. This feature is available for Kubernetes 1.16 and later releases.
          allowVolumeExpansion: true
          additionalParameters: { "topolvm.io/device-class": "main-thin" }
          # mount options
          mountOptions: []
