---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vlogs
  namespace: vlogs
spec:
  chartRef:
    kind: OCIRepository
    name: vlogs
  interval: 1h
  values:
    nameOverride: vlogs
    server:
      retentionPeriod: 30d
      service:
        type: LoadBalancer
        CLusterIP: 192.168.0.94
        annotations:
          metallb.io/ip-allocated-from-pool: main
          metallb.io/loadBalancerIPs: 192.168.0.94
      http:
        - name: http
          primary: true
          value: ":9443"
      syslog:
        tcp:
          - name: syslog-tcp
            value: :514
      nodeSelector:
        kubernetes.io/hostname: k8s-control-1

