---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: truenas-external-service
  namespace: truenas-external-service
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 17.6.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    route:
      main:
        enabled: true
        kind: HTTPRoute
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Default
          gethomepage.dev/href: https://truenas.${DOMAIN_0}/
          gethomepage.dev/icon: "https://truenas.${INGRESS_URL}/ui/assets/images/truenas_scale_ondark_favicon.png"
          gethomepage.dev/name: TrueNAS Scale
          gethomepage.dev/instance: "internal"
          gethomepage.dev/ping: ${TRUENAS_EXTERNAL_IP}
          gethomepage.dev/description: NAS Appliance OS
          gethomepage.dev/widget.type: truenas
          gethomepage.dev/widget.url: http://${TRUENAS_EXTERNAL_IP}:81
          gethomepage.dev/widget.key: ${TRUENAS_API_KEY} # not required if using username / password
          gethomepage.dev/widget.enablePools: "true" # optional, defaults to false
          gethomepage.dev/widget.nasType: scale # def
        parentRefs:
          - name: envoy-internal
            namespace: envoy
            sectionName: https
        hostnames:
          - truenas.${DOMAIN_0}

    service:
      main:
        type: ExternalIP
        externalIP: "${TRUENAS_EXTERNAL_IP}"
        useSlice: false
        ports:
          main:
            protocol: http
            port: 81
            # Target port is the port of the "external service"
            # Defaults to "port" if not set
    workload:
      main:
        enabled: false
        podSpec:
          containers:
            main:
              env: {}
