---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: truenas-external-service
  namespace: truenas-external-service
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 15.2.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      main:
        enabled: true
        annotations:
          traefik.frontend.passHostHeader: "false"
        hosts:
          - host: truenas.${INGRESS_URL}
            paths:
              - path: /
                pathType: Prefix
                overrideService:
                  name: main
                  port: 444
        tls:
          - hosts:
              - truenas.${INGRESS_URL}
            certificateIssuer: "domain-0-le-prod"
        integrations:
          certManager:
            enabled: true
            certificateIssuer: "domain-0-le-prod"
          homepage:
            enabled: true
            group: Default
            icon: "https://truenas.${INGRESS_URL}/ui/assets/images/truenas_scale_ondark_favicon.png"
            name: "TrueNAS Scale"
            widget:
              type: truenas
              url: http://${TRUENAS_EXTERNAL_IP}:81
              custom:
                key: ${TRUENAS_API_KEY} # not required if using username / password
                enablePools: "true" # optional, defaults to false
                nasType: scale # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core

    service:
      main:
        type: ExternalIP
        externalIP: "${TRUENAS_EXTERNAL_IP}"
        useSlice: false
        ports:
          main:
            protocol: https
            port: 444
            # Target port is the port of the "external service"
            # Defaults to "port" if not set
    workload:
      main:
        enabled: false
        podSpec:
          containers:
            main:
              env: {}
